export enum CharacterType {
    abberration = 'abberration',
    beast = 'beast',
    celestial = 'celestial',
    construct = 'construct',
    dragon = 'dragon',
    elemental = 'elemental',
    fey = 'fey',
    fiend = 'fiend',
    demon = 'demon',
    devil = 'devil',
    shapechanger = 'shapechanger',
    giant = 'giant',
    humanoid = 'humanoid',
    monstrosity = 'monstrosity',
    ooze = 'ooze',
    plant = 'plant',
    undead = 'undead',
    summoned = 'summoned',
    magical = 'magical',
    vermin = 'vermin',
    none = 'none',
    slime = 'slime',
    insect = 'insect',
}