import { RaceEnum } from "../../../Common/RequestResponse/characterCreation";
import { CharacterType } from "../../Entities/Character/Subclasses/CharacterType";
import { CharacterDB } from "./CharacterDB";

export function createCharacterDB(overrides: Partial<CharacterDB> = {}): CharacterDB {
    const defaultCharacterDB: CharacterDB = {
        id: "",
        partyID: "none",
        name: "Unnamed Character",
        type: CharacterType.none,
        gender: "NONE",
        portrait: null,
        background: "",
        race: RaceEnum.UNDEFINED,
        alignment: {
            good: 0,
            evil: 0,
            law: 0,
            chaos: 0,
        },
        mood: 100,
        energy: 100,
        fame: 0,
        level: 1,
        gold: 0,
        exp: 0,
        isDead: false,
        lastTarget: null,
        raceHP: 10,
        raceMP: 10,
        raceSP: 10,
        baseHP: 10,
        baseMP: 10,
        baseSP: 10,
        bonusHP: 0,
        bonusMP: 0,
        bonusSP: 0,
        currentHP: 10,
        currentMP: 10,
        currentSP: 10,
        status: {
            attributes: {
                charisma: { base: 10, bonus: 0, battle: 0, exp: 0 },
                luck: { base: 10, bonus: 0, battle: 0, exp: 0 },
                intelligence: { base: 10, bonus: 0, battle: 0, exp: 0 },
                leadership: { base: 10, bonus: 0, battle: 0, exp: 0 },
                vitality: { base: 10, bonus: 0, battle: 0, exp: 0 },
                willpower: { base: 10, bonus: 0, battle: 0, exp: 0 },
                breath: { base: 10, bonus: 0, battle: 0, exp: 0 },
                planar: { base: 10, bonus: 0, battle: 0, exp: 0 },
                dexterity: { base: 10, bonus: 0, battle: 0, exp: 0 },
                agility: { base: 10, bonus: 0, battle: 0, exp: 0 },
                strength: { base: 10, bonus: 0, battle: 0, exp: 0 },
                endurance: { base: 10, bonus: 0, battle: 0, exp: 0 },
            },
            proficiencies: {
                bareHand: { base: 0, bonus: 0, battle: 0, exp: 0 },
                sword: { base: 0, bonus: 0, battle: 0, exp: 0 },
                blade: { base: 0, bonus: 0, battle: 0, exp: 0 },
                dagger: { base: 0, bonus: 0, battle: 0, exp: 0 },
                spear: { base: 0, bonus: 0, battle: 0, exp: 0 },
                axe: { base: 0, bonus: 0, battle: 0, exp: 0 },
                mace: { base: 0, bonus: 0, battle: 0, exp: 0 },
                shield: { base: 0, bonus: 0, battle: 0, exp: 0 },
                bow: { base: 0, bonus: 0, battle: 0, exp: 0 },
                magicWand: { base: 0, bonus: 0, battle: 0, exp: 0 },
                staff: { base: 0, bonus: 0, battle: 0, exp: 0 },
                tome: { base: 0, bonus: 0, battle: 0, exp: 0 },
                orb: { base: 0, bonus: 0, battle: 0, exp: 0 },
            },
            battlers: {
                pATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                pHIT: { base: 0, bonus: 0, battle: 0, exp: 0 },
                pCRT: { base: 0, bonus: 0, battle: 0, exp: 0 },
                pDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                mATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                mHIT: { base: 0, bonus: 0, battle: 0, exp: 0 },
                mCRT: { base: 0, bonus: 0, battle: 0, exp: 0 },
                mDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chiWarmATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chiColdATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chiWarmDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chiColdDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                slash: { base: 0, bonus: 0, battle: 0, exp: 0 },
                pierce: { base: 0, bonus: 0, battle: 0, exp: 0 },
                blunt: { base: 0, bonus: 0, battle: 0, exp: 0 },
                slashDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                pierceDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                bluntDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                dodge: { base: 0, bonus: 0, battle: 0, exp: 0 },
                orderATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chaosATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                geoATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                waterATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                airATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                fireATK: { base: 0, bonus: 0, battle: 0, exp: 0 },
                orderDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chaosDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                geoDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                waterDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                airDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
                fireDEF: { base: 0, bonus: 0, battle: 0, exp: 0 },
            },
            elements: {
                order: { base: 0, bonus: 0, battle: 0, exp: 0 },
                chaos: { base: 0, bonus: 0, battle: 0, exp: 0 },
                geo: { base: 0, bonus: 0, battle: 0, exp: 0 },
                water: { base: 0, bonus: 0, battle: 0, exp: 0 },
                air: { base: 0, bonus: 0, battle: 0, exp: 0 },
                fire: { base: 0, bonus: 0, battle: 0, exp: 0 },
            },
            artisans: {
                mining: { base: 0, bonus: 0, battle: 0, exp: 0 },
                smithing: { base: 0, bonus: 0, battle: 0, exp: 0 },
                woodcutting: { base: 0, bonus: 0, battle: 0, exp: 0 },
                carpentry: { base: 0, bonus: 0, battle: 0, exp: 0 },
                foraging: { base: 0, bonus: 0, battle: 0, exp: 0 },
                weaving: { base: 0, bonus: 0, battle: 0, exp: 0 },
                skinning: { base: 0, bonus: 0, battle: 0, exp: 0 },
                tanning: { base: 0, bonus: 0, battle: 0, exp: 0 },
                jewelry: { base: 0, bonus: 0, battle: 0, exp: 0 },
                cooking: { base: 0, bonus: 0, battle: 0, exp: 0 },
                alchemy: { base: 0, bonus: 0, battle: 0, exp: 0 },
                enchanting: { base: 0, bonus: 0, battle: 0, exp: 0 },
            },
        },
        equipments: {
            mainHand: null,
            offHand: null,
            armor: null,
            cloth: null,
            headWear: null,
            necklace: null,
            ring: null,
        },
        internals: [],
        activeInternal: null,
        traits: [],
        skills: [],
        activeSkills: [],
        position: 0,
        itemsBag: {},
        baseAC: 7,
        location: "unknown",
        isSummoned: false,
        arcaneAptitude: 0,
        bagSize: 20,
        storyFlags: {
            finishedStartingEvent: false,
        },
        relation: {},
    };

    // Merge the overrides with the default values
    return { ...defaultCharacterDB, ...overrides };
}