import { RelationEnum } from "../../../Common/Enums/RelationEnums";
import { RaceEnum } from "../../../Common/RequestResponse/characterCreation";
import { CharacterType } from "../../Entities/Character/Subclasses/CharacterType";
import { GearSeedArmorEnum } from "../Item/Gear/Seeds/Armor";
import { ClothSeedEnum } from "../Item/Gear/Seeds/Cloth";
import { GearSeedHeadwearEnum } from "../Item/Gear/Seeds/HeadWear";
import { NecklaceSeedEnum } from "../Item/Gear/Seeds/Necklace";
import { RingSeedEnum } from "../Item/Gear/Seeds/Ring";
import { GearSeedWeaponEnum } from "../Item/Gear/Seeds/Weapon";
import { CharacterDB } from "./Characters";

export const NPCID = {
    npc_king_edmund_azure: "npc_king_edmund_azure",
    npc_queen_elara_azure: "npc_queen_elara_azure",
    npc_princess_lysandra_azure: "npc_princess_lysandra_azure",
    npc_archmagus_vaelin: "npc_archmagus_vaelin",
    npc_grand_abbot_zhenwu: "npc_grand_abbot_zhenwu",
    npc_li_tianming: "npc_li_tianming",
    npc_li_xueyue: "npc_li_xueyue",
    npc_karin_farsee: "npc_karin_farsee",
}

export const NPCCharacterSeed: CharacterDB[] = [
    //MARK::NPC
    //MARK: EDMUND AZURE
    {
        id: NPCID.npc_king_edmund_azure,
        partyID: NPCID.npc_king_edmund_azure,
        name: "King Edmund Azure",
        type: CharacterType.humanoid,
        gender: "MALE",
        portrait: "king_edmund.png",
        background: "King of Ocean Tide, a great warrior and leader",
        race: RaceEnum.HUMAN,
        alignment: { good: 60, evil: 10, law: 100, chaos: 20 },
        mood: 100,
        energy: 100,
        fame: 10000,
        level: 7,
        gold: 0,
        exp: 0,
        isDead: false,
        lastTarget: "",
        raceHP: 6,
        raceMP: 6,
        raceSP: 6,
        baseHP: 56,
        baseMP: 41,
        baseSP: 48,
        currentHP: 50,
        currentMP: 35,
        currentSP: 62,
        status: {
            attributes: {
                charisma: { base: 14, bonus: 0, battle:0, exp: 0 },
                luck: { base: 12, bonus: 0, battle: 0, exp: 0 },
                intelligence: { base: 14, bonus:0, battle:0, exp: 0 },
                leadership: { base: 16, bonus:0, battle:0, exp: 0 },
                vitality: { base: 14, bonus:0, battle:0, exp: 0 },
                willpower: { base: 10, bonus:0, battle:0, exp: 0 },
                breath: { base: 8, bonus:0, battle:0, exp: 0 },
                planar: { base: 10, bonus:0, battle:0, exp: 0 },
                dexterity: { base: 12, bonus:0, battle:0, exp: 0 },
                agility: { base: 10, bonus:0, battle:0, exp: 0 },
                strength: { base: 16, bonus:0, battle:0, exp: 0 },
                endurance: { base: 16, bonus:0, battle:0, exp: 0 },
            },
            proficiencies: {
                bareHand: { base: 5, bonus:0, battle:0, exp: 0 },
                sword: { base: 18, bonus:0, battle:0, exp: 0 },
                blade: { base: 15, bonus:0, battle:0, exp: 0 },
                dagger: { base: 10, bonus:0, battle:0, exp: 0 },
                spear: { base: 12, bonus:0, battle:0, exp: 0 },
                axe: { base: 16, bonus:0, battle:0, exp: 0 },
                mace: { base: 14, bonus:0, battle:0, exp: 0 },
                shield: { base: 20, bonus:0, battle:0, exp: 0 },
                bow: { base: 8, bonus:0, battle:0, exp: 0 },
                magicWand: { base: 0, bonus:0, battle:0, exp: 0 },
                staff: { base: 0, bonus:0, battle:0, exp: 0 },
                tome: { base: 0, bonus:0, battle:0, exp: 0 },
                orb: { base: 0, bonus:0, battle:0, exp: 0 },
            },
            battlers: {
                pATK: { base: 20, bonus:0, battle:0, exp: 0 },
                pHIT: { base: 18, bonus:0, battle:0, exp: 0 },
                pCRT: { base: 15, bonus:0, battle:0, exp: 0 },
                pDEF: { base: 22, bonus:0, battle:0, exp: 0 },
                mATK: { base: 10, bonus:0, battle:0, exp: 0 },
                mHIT: { base: 9, bonus:0, battle:0, exp: 0 },
                mCRT: { base: 8, bonus:0, battle:0, exp: 0 },
                mDEF: { base: 14, bonus:0, battle:0, exp: 0 },
                chiWarmATK: { base: 0, bonus:0, battle:0, exp: 0 },
                chiColdATK: { base: 0, bonus:0, battle:0, exp: 0 },
                chiWarmDEF: { base: 0, bonus:0, battle:0, exp: 0 },
                chiColdDEF: { base: 0, bonus:0, battle:0, exp: 0 },
                slash: { base: 18, bonus:0, battle:0, exp: 0 },
                pierce: { base: 15, bonus:0, battle:0, exp: 0 },
                blunt: { base: 17, bonus:0, battle:0, exp: 0 },
                slashDEF: { base: 18, bonus:0, battle:0, exp: 0 },
                pierceDEF: { base: 15, bonus:0, battle:0, exp: 0 },
                bluntDEF: { base: 17, bonus:0, battle:0, exp: 0 },
                dodge: { base: 12, bonus:0, battle:0, exp: 0 },
                orderATK: {base: 0, bonus:0, battle: 0, exp: 0 },
                chaosATK: {base: 0, bonus:0, battle: 0, exp: 0 },
                geoATK: { base: 0, bonus:0, battle: 0, exp: 0 },
                waterATK: { base: 0, bonus:0, battle: 0, exp: 0 },
                airATK: { base: 0, bonus:0, battle: 0, exp: 0 },
                fireATK: { base: 0, bonus:0, battle: 0, exp: 0 },
                orderDEF: { base: 0, bonus:0, battle: 0, exp: 0 },
                chaosDEF: { base: 0, bonus:0, battle: 0, exp: 0 },
                geoDEF: { base: 0, bonus:0, battle: 0, exp: 0 },
                waterDEF: { base: 0, bonus:0, battle: 0, exp: 0 },
                airDEF: { base: 0, bonus:0, battle: 0, exp: 0 },
                fireDEF: { base: 0, bonus:0, battle: 0, exp: 0 }
            },
            elements: {
                order: { base: 0,bonus:0, battle: 0, exp: 0 },
                chaos: { base: 0,bonus:0, battle: 0, exp: 0 },
                geo: { base: 0,bonus:0, battle: 0, exp: 0 },
                water: { base: 1,bonus:0, battle: 0, exp: 0 },
                air: { base: 0,bonus:0, battle: 0, exp: 0 },
                fire: { base: 0,bonus:0, battle: 0, exp: 0 },
            },
            artisans: {
                mining: { base: 0, bonus:0, battle:0, exp: 0 },
                smithing: { base: 10, bonus:0, battle:0, exp: 0 },
                woodcutting: { base: 7, bonus:0, battle:0, exp: 0 },
                carpentry: { base: 5, bonus:0, battle:0, exp: 0 },
                foraging: { base: 0, bonus:0, battle:0, exp: 0 },
                weaving: { base: 0, bonus:0, battle:0, exp: 0 },
                skinning: { base: 0, bonus:0, battle:0, exp: 0 },
                tanning: { base: 0, bonus:0, battle:0, exp: 0 },
                jewelry: { base: 0, bonus:0, battle:0, exp: 0 },
                alchemy: { base: 3, bonus:0, battle:0, exp: 0 },
                cooking: { base: 0, bonus:0, battle:0, exp: 0 },
                enchanting: { base: 0, bonus:0, battle:0, exp: 0 },
            }
        },
        equipments: {
            mainHand: GearSeedWeaponEnum.AzureScepter,
            offHand: GearSeedWeaponEnum.SteelTowerShield,
            armor: GearSeedArmorEnum.armor_medium_mithril,
            necklace: NecklaceSeedEnum.necklace_amulet_gold_perfect_diamond,
            ring: RingSeedEnum.ring_signet_gold_aquamarine,
            cloth: ClothSeedEnum.cloth_eldritch_mammoth_wool,
            headWear: GearSeedHeadwearEnum.headwear_circlet_mithril,
        },
        internals: [],
        activeInternal: null,
        traits: ["Leader", "Strategist", "Commander"],
        skills: [
            // { skillID: "slash_attack", level: 5, exp: 0 },
            // { skillID: "shield_bash", level: 3, exp: 0 }
        ],
        activeSkills: [
            // { skillID: "shield_bash", level: 3, exp: 0 }
        ],
        position: 1,
        itemsBag: [],
        baseAC: 7,
        location: "Ocean Tide Castle",
        isSummoned: false,
        arcaneAptitude: 70,
        bagSize: 20,
        relation: {
            [NPCID.npc_queen_elara_azure]: { value: 100, status: RelationEnum.Spouse },
            [NPCID.npc_princess_lysandra_azure]: { value: 100, status: RelationEnum.Family },
        },
    },
]