import { RaceEnum } from "../../../Common/RequestResponse/characterCreation";
import { CharacterArchetype } from "../../Entities/Character/Subclasses/CharacterArchetype";
import { CharacterStatus } from "../../Entities/Character/Subclasses/CharacterStatus";
import { CharacterType } from "../../Entities/Character/Subclasses/CharacterType";
import { GearSeedArmorEnum } from "../Item/Gear/Seeds/Armor";
import { GearSeedWeaponEnum } from "../Item/Gear/Seeds/Weapon";
import { SkillEnum } from "../Skill/skill";
import {
	classModifierBarbarian,
	classModifierChieftain,
	classModifierCleric,
	classModifierFighter,
	classModifierMage,
	classModifierRanger,
	classModifierWarlock,
} from "./ClassModifier";
import { orcRace, RaceStatus } from "./RacesStatus";

// let's make an average stats range for an Orc
/*
Orc are one of the common found race throughout the world. They are known for their strength and endurance.
They are usually found in the wilderness, living in tribes or clans. They are known for their aggressive nature and their love for battle.

New approach to NPCs, we want a more vibrant and diverse world where all NPCs are unique and have their own stories.
So, we're not going to call them just like, "Orc Warrior", "Orc Archer", etc. We're going to give them names and backgrounds.
*/

export const OrcID = {
	orc_sword_m: "orc_sword_m",
	orc_sword_f: "orc_sword_f",
	orc_greatsword_m: "orc_greatsword_m",
	orc_greatsword_f: "orc_greatsword_f",
	orc_greataxe_m: "orc_greataxe_m",
	orc_greataxe_f: "orc_greataxe_f",
	orc_bow_m: "orc_bow_m",
	orc_bow_f: "orc_bow_f",
	// Wand are cleric, staff are mage
	orc_wand_m: "orc_wand_m",
	orc_wand_f: "orc_wand_f",
	orc_staff_m: "orc_staff_m",
	orc_staff_f: "orc_staff_f",

	orc_chieftain_warrior_m: "orc_chieftain_m",
	orc_chieftain_warrior_f: "orc_chieftain_f",
	orc_chieftain_warlock_m: "orc_chieftain_m",
	orc_chieftain_warlock_f: "orc_chieftain_f",
};

let attributes = {
	strength: { base: orcRace.strength, exp: 0 },
	charisma: { base: orcRace.charisma, exp: 0 },
	luck: { base: orcRace.luck, exp: 0 },
	intelligence: { base: orcRace.intelligence, exp: 0 },
    leadership: { base: orcRace.leadership, exp: 0 },
	vitality: { base: orcRace.vitality, exp: 0 },
	willpower: { base: orcRace.willpower, exp: 0 },
	breath: { base: orcRace.breath, exp: 0 },
	planar: { base: orcRace.planar, exp: 0 },
	dexterity: { base: orcRace.dexterity, exp: 0 },
	agility: { base: orcRace.agility, exp: 0 },
	endurance: { base: orcRace.endurance, exp: 0 },
};

let proficiencies = {
	bareHand: { base: 0, exp: 0 },
	sword: { base: 0, exp: 0 },
	blade: { base: 0, exp: 0 },
	dagger: { base: 0, exp: 0 },
	spear: { base: 0, exp: 0 },
	axe: { base: 0, exp: 0 },
	mace: { base: 0, exp: 0 },
	shield: { base: 0, exp: 0 },
	bow: { base: 0, exp: 0 },
	magicWand: { base: 0, exp: 0 },
	staff: { base: 0, exp: 0 },
	tome: { base: 0, exp: 0 },
	orb: { base: 0, exp: 0 },
};

let battlers = {
	pATK: { base: 0, exp: 0 },
	pHIT: { base: 0, exp: 0 },
	pCRT: { base: 0, exp: 0 },
	pDEF: { base: 0, exp: 0 },
	mATK: { base: 0, exp: 0 },
	mHIT: { base: 0, exp: 0 },
	mCRT: { base: 0, exp: 0 },
	mDEF: { base: 0, exp: 0 },
	chiWarmATK: { base: 0, exp: 0 },
	chiColdATK: { base: 0, exp: 0 },
	chiWarmDEF: { base: 0, exp: 0 },
	chiColdDEF: { base: 0, exp: 0 },
	slash: { base: 0, exp: 0 },
	pierce: { base: 0, exp: 0 },
	blunt: { base: 0, exp: 0 },
	slashDEF: { base: 18, exp: 0 },
    pierceDEF: { base: 15, exp: 0 },
    bluntDEF: { base: 17, exp: 0 },
	dodge: { base: 0, exp: 0 },
	orderATK: {
		base: 0,
		exp: 0
	},
	chaosATK: {
		base: 0,
		exp: 0
	},
	geoATK: {
		base: 0,
		exp: 0
	},
	waterATK: {
		base: 0,
		exp: 0
	},
	airATK: {
		base: 0,
		exp: 0
	},
	fireATK: {
		base: 0,
		exp: 0
	},
	orderDEF: {
		base: 0,
		exp: 0
	},
	chaosDEF: {
		base: 0,
		exp: 0
	},
	geoDEF: {
		base: 0,
		exp: 0
	},
	waterDEF: {
		base: 0,
		exp: 0
	},
	airDEF: {
		base: 0,
		exp: 0
	},
	fireDEF: {
		base: 0,
		exp: 0
	}
};

let elements = {
	order: { base: 0, exp: 0 },
	chaos: { base: 0, exp: 0 },
	geo: { base: 0, exp: 0 },
	water: { base: 0, exp: 0 },
	air: { base: 0, exp: 0 },
	fire: { base: 0, exp: 0 },
};

let artisans = {
	mining: { base: 0, exp: 0 },
	smithing: { base: 0, exp: 0 },
	woodcutting: { base: 0, exp: 0 },
	carpentry: { base: 0, exp: 0 },
	foraging: { base: 0, exp: 0 },
	weaving: { base: 0, exp: 0 },
	skinning: { base: 0, exp: 0 },
	tanning: { base: 0, exp: 0 },
	jewelry: { base: 0, exp: 0 },
	cooking: { base: 0, exp: 0 },
	alchemy: { base: 0, exp: 0 },
	enchanting: { base: 0, exp: 0 },
};

let traits = orcRace.traits;

export const OrcSeed: CharacterArchetype[] = [
	new CharacterArchetype({
		name: "Orc",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_sword_m,
		level: 5,
		portrait: "orc_sword_m",
		race: RaceEnum.ORC,
		background: "An orc warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.IronLongSword,
			offHand: GearSeedWeaponEnum.IronRoundShield,
			armor: GearSeedArmorEnum.armor_medium_chainmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_shield_bash, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierFighter,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_sword_f,
		level: 5,
		portrait: "orc_sword_f",
		race: RaceEnum.ORC,
		background: "An orc warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.IronLongSword,
			offHand: GearSeedWeaponEnum.IronRoundShield,
			armor: GearSeedArmorEnum.armor_medium_chainmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_shield_bash, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierFighter,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_greatsword_m,
		level: 5,
		portrait: "orc_greatsword_m",
		race: RaceEnum.ORC,
		background: "An orc warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes: {
			charisma: { base: 5, exp: 0 },
			luck: { base: 6, exp: 0 },
			intelligence: { base: 8, exp: 0 },
			leadership: { base: 4, exp: 0 },
			vitality: { base: 10, exp: 0 },
			willpower: { base: 4, exp: 0 },
			breath: { base: 6, exp: 0 },
			planar: { base: 5, exp: 0 },
			dexterity: { base: 10, exp: 0 },
			agility: { base: 8, exp: 0 },
			strength: { base: 12, exp: 0 },
			endurance: { base: 10, exp: 0 },
		},
		proficiencies: {
			bareHand: { base: 5, exp: 0 },
			sword: { base: 0, exp: 0 },
			blade: { base: 8, exp: 0 },
			dagger: { base: 4, exp: 0 },
			spear: { base: 5, exp: 0 },
			axe: { base: 8, exp: 0 },
			mace: { base: 6, exp: 0 },
			shield: { base: 7, exp: 0 },
			bow: { base: 3, exp: 0 },
			magicWand: { base: 0, exp: 0 },
			staff: { base: 0, exp: 0 },
			tome: { base: 0, exp: 0 },
			orb: { base: 0, exp: 0 },
		},
		battlers: {
			pATK: { base: 0, exp: 0 },
			pHIT: { base: 0, exp: 0 },
			pCRT: { base: 0, exp: 0 },
			pDEF: { base: 0, exp: 0 },
			mATK: { base: 0, exp: 0 },
			mHIT: { base: 0, exp: 0 },
			mCRT: { base: 0, exp: 0 },
			mDEF: { base: 0, exp: 0 },
			chiWarmATK: { base: 0, exp: 0 },
			chiColdATK: { base: 0, exp: 0 },
			chiWarmDEF: { base: 0, exp: 0 },
			chiColdDEF: { base: 0, exp: 0 },
			slash: { base: 0, exp: 0 },
			pierce: { base: 0, exp: 0 },
			blunt: { base: 0, exp: 0 },
			slashDEF: { base: 18, exp: 0 },
    		pierceDEF: { base: 15, exp: 0 },
    		bluntDEF: { base: 17, exp: 0 },
			dodge: { base: 0, exp: 0 },
			orderATK: {
                base: 0,
                exp: 0
            },
            chaosATK: {
                base: 0,
                exp: 0
            },
            geoATK: {
                base: 0,
                exp: 0
            },
            waterATK: {
                base: 0,
                exp: 0
            },
            airATK: {
                base: 0,
                exp: 0
            },
            fireATK: {
                base: 0,
                exp: 0
            },
            orderDEF: {
                base: 0,
                exp: 0
            },
            chaosDEF: {
                base: 0,
                exp: 0
            },
            geoDEF: {
                base: 0,
                exp: 0
            },
            waterDEF: {
                base: 0,
                exp: 0
            },
            airDEF: {
                base: 0,
                exp: 0
            },
            fireDEF: {
                base: 0,
                exp: 0
            }
		},
		elements: {
			order: { base: 0, exp: 0 },
			chaos: { base: 0, exp: 0 },
			geo: { base: 0, exp: 0 },
			water: { base: 0, exp: 0 },
			air: { base: 0, exp: 0 },
			fire: { base: 0, exp: 0 },
		},
		artisans: {
			mining: { base: 0, exp: 0 },
			smithing: { base: 0, exp: 0 },
			woodcutting: { base: 0, exp: 0 },
			carpentry: { base: 0, exp: 0 },
			foraging: { base: 0, exp: 0 },
			weaving: { base: 0, exp: 0 },
			skinning: { base: 0, exp: 0 },
			tanning: { base: 0, exp: 0 },
			jewelry: { base: 0, exp: 0 },
			alchemy: { base: 0, exp: 0 },
			cooking: { base: 0, exp: 0 },
			enchanting: { base: 0, exp: 0 },
		},
		equipments: {
			mainHand: GearSeedWeaponEnum.IronGreatSword,
			offHand: null,
			armor: GearSeedArmorEnum.armor_medium_chainmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits: [],
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_cleave, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierBarbarian,
	}),
	new CharacterArchetype({
		name: "Orc",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_greatsword_f,
		level: 5,
		portrait: "orc_greatsword_f",
		race: RaceEnum.ORC,
		background: "An orc warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes: {
			charisma: { base: 5, exp: 0 },
			luck: { base: 6, exp: 0 },
			intelligence: { base: 10, exp: 0 },
			leadership: { base: 4, exp: 0 },
			vitality: { base: 10, exp: 0 },
			willpower: { base: 4, exp: 0 },
			breath: { base: 6, exp: 0 },
			planar: { base: 5, exp: 0 },
			dexterity: { base: 11, exp: 0 },
			agility: { base: 8, exp: 0 },
			strength: { base: 10, exp: 0 },
			endurance: { base: 10, exp: 0 },
		},
		proficiencies: {
			bareHand: { base: 5, exp: 0 },
			sword: { base: 0, exp: 0 },
			blade: { base: 8, exp: 0 },
			dagger: { base: 4, exp: 0 },
			spear: { base: 5, exp: 0 },
			axe: { base: 8, exp: 0 },
			mace: { base: 6, exp: 0 },
			shield: { base: 7, exp: 0 },
			bow: { base: 3, exp: 0 },
			magicWand: { base: 0, exp: 0 },
			staff: { base: 0, exp: 0 },
			tome: { base: 0, exp: 0 },
			orb: { base: 0, exp: 0 },
		},
		battlers: {
			pATK: { base: 0, exp: 0 },
			pHIT: { base: 0, exp: 0 },
			pCRT: { base: 0, exp: 0 },
			pDEF: { base: 0, exp: 0 },
			mATK: { base: 0, exp: 0 },
			mHIT: { base: 0, exp: 0 },
			mCRT: { base: 0, exp: 0 },
			mDEF: { base: 0, exp: 0 },
			chiWarmATK: { base: 0, exp: 0 },
			chiColdATK: { base: 0, exp: 0 },
			chiWarmDEF: { base: 0, exp: 0 },
			chiColdDEF: { base: 0, exp: 0 },
			slash: { base: 0, exp: 0 },
			pierce: { base: 0, exp: 0 },
			blunt: { base: 0, exp: 0 },
			slashDEF: { base: 18, exp: 0 },
    		pierceDEF: { base: 15, exp: 0 },
    		bluntDEF: { base: 17, exp: 0 },
			dodge: { base: 0, exp: 0 },
            orderATK: {
                base: 0,
                exp: 0
            },
            chaosATK: {
                base: 0,
                exp: 0
            },
            geoATK: {
                base: 0,
                exp: 0
            },
            waterATK: {
                base: 0,
                exp: 0
            },
            airATK: {
                base: 0,
                exp: 0
            },
            fireATK: {
                base: 0,
                exp: 0
            },
            orderDEF: {
                base: 0,
                exp: 0
            },
            chaosDEF: {
                base: 0,
                exp: 0
            },
            geoDEF: {
                base: 0,
                exp: 0
            },
            waterDEF: {
                base: 0,
                exp: 0
            },
            airDEF: {
                base: 0,
                exp: 0
            },
            fireDEF: {
                base: 0,
                exp: 0
            }
		},
		elements: {
			order: { base: 0, exp: 0 },
			chaos: { base: 0, exp: 0 },
			geo: { base: 0, exp: 0 },
			water: { base: 0, exp: 0 },
			air: { base: 0, exp: 0 },
			fire: { base: 0, exp: 0 },
		},
		artisans: {
			mining: { base: 0, exp: 0 },
			smithing: { base: 0, exp: 0 },
			woodcutting: { base: 0, exp: 0 },
			carpentry: { base: 0, exp: 0 },
			foraging: { base: 0, exp: 0 },
			weaving: { base: 0, exp: 0 },
			skinning: { base: 0, exp: 0 },
			tanning: { base: 0, exp: 0 },
			jewelry: { base: 0, exp: 0 },
			alchemy: { base: 0, exp: 0 },
			cooking: { base: 0, exp: 0 },
			enchanting: { base: 0, exp: 0 },
		},
		equipments: {
			mainHand: GearSeedWeaponEnum.IronGreatSword,
			offHand: null,
			armor: GearSeedArmorEnum.armor_medium_chainmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits: [],
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_cleave, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierBarbarian,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_greataxe_m,
		level: 5,
		portrait: "orc_greataxe_m",
		race: RaceEnum.ORC,
		background: "An orc warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes: {
			charisma: { base: 5, exp: 0 },
			luck: { base: 6, exp: 0 },
			intelligence: { base: 7, exp: 0 },
			leadership: { base: 4, exp: 0 },
			vitality: { base: 11, exp: 0 },
			willpower: { base: 4, exp: 0 },
			breath: { base: 6, exp: 0 },
			planar: { base: 5, exp: 0 },
			dexterity: { base: 10, exp: 0 },
			agility: { base: 8, exp: 0 },
			strength: { base: 13, exp: 0 },
			endurance: { base: 11, exp: 0 },
		},
		proficiencies: {
			bareHand: { base: 5, exp: 0 },
			sword: { base: 0, exp: 0 },
			blade: { base: 8, exp: 0 },
			dagger: { base: 4, exp: 0 },
			spear: { base: 5, exp: 0 },
			axe: { base: 10, exp: 0 },
			mace: { base: 6, exp: 0 },
			shield: { base: 7, exp: 0 },
			bow: { base: 3, exp: 0 },
			magicWand: { base: 0, exp: 0 },
			staff: { base: 0, exp: 0 },
			tome: { base: 0, exp: 0 },
			orb: { base: 0, exp: 0 },
		},
		battlers: {
			pATK: { base: 0, exp: 0 },
			pHIT: { base: 0, exp: 0 },
			pCRT: { base: 0, exp: 0 },
			pDEF: { base: 0, exp: 0 },
			mATK: { base: 0, exp: 0 },
			mHIT: { base: 0, exp: 0 },
			mCRT: { base: 0, exp: 0 },
			mDEF: { base: 0, exp: 0 },
			chiWarmATK: { base: 0, exp: 0 },
			chiColdATK: { base: 0, exp: 0 },
			chiWarmDEF: { base: 0, exp: 0 },
			chiColdDEF: { base: 0, exp: 0 },
			slash: { base: 0, exp: 0 },
			pierce: { base: 0, exp: 0 },
			blunt: { base: 0, exp: 0 },
			slashDEF: { base: 18, exp: 0 },
    		pierceDEF: { base: 15, exp: 0 },
    		bluntDEF: { base: 17, exp: 0 },
			dodge: { base: 0, exp: 0 },
			orderATK: {
                base: 0,
                exp: 0
            },
            chaosATK: {
                base: 0,
                exp: 0
            },
            geoATK: {
                base: 0,
                exp: 0
            },
            waterATK: {
                base: 0,
                exp: 0
            },
            airATK: {
                base: 0,
                exp: 0
            },
            fireATK: {
                base: 0,
                exp: 0
            },
            orderDEF: {
                base: 0,
                exp: 0
            },
            chaosDEF: {
                base: 0,
                exp: 0
            },
            geoDEF: {
                base: 0,
                exp: 0
            },
            waterDEF: {
                base: 0,
                exp: 0
            },
            airDEF: {
                base: 0,
                exp: 0
            },
            fireDEF: {
                base: 0,
                exp: 0
            }
		},
		elements: {
			order: { base: 0, exp: 0 },
			chaos: { base: 0, exp: 0 },
			geo: { base: 0, exp: 0 },
			water: { base: 0, exp: 0 },
			air: { base: 0, exp: 0 },
			fire: { base: 0, exp: 0 },
		},
		artisans: {
			mining: { base: 0, exp: 0 },
			smithing: { base: 0, exp: 0 },
			woodcutting: { base: 0, exp: 0 },
			carpentry: { base: 0, exp: 0 },
			foraging: { base: 0, exp: 0 },
			weaving: { base: 0, exp: 0 },
			skinning: { base: 0, exp: 0 },
			tanning: { base: 0, exp: 0 },
			jewelry: { base: 0, exp: 0 },
			alchemy: { base: 0, exp: 0 },
			cooking: { base: 0, exp: 0 },
			enchanting: { base: 0, exp: 0 },
		},
		equipments: {
			mainHand: GearSeedWeaponEnum.IronGreatAxe,
			offHand: null,
			armor: GearSeedArmorEnum.armor_medium_chainmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits: [],
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_cleave, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierBarbarian,
	}),
	new CharacterArchetype({
		name: "Orc",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_greataxe_f,
		level: 5,
		portrait: "orc_greataxe_f",
		race: RaceEnum.ORC,
		background: "An orc warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes: {
			charisma: { base: 5, exp: 0 },
			luck: { base: 6, exp: 0 },
			intelligence: { base: 9, exp: 0 },
			leadership: { base: 4, exp: 0 },
			vitality: { base: 10, exp: 0 },
			willpower: { base: 4, exp: 0 },
			breath: { base: 6, exp: 0 },
			planar: { base: 5, exp: 0 },
			dexterity: { base: 11, exp: 0 },
			agility: { base: 8, exp: 0 },
			strength: { base: 11, exp: 0 },
			endurance: { base: 10, exp: 0 },
		},
		proficiencies: {
			bareHand: { base: 5, exp: 0 },
			sword: { base: 0, exp: 0 },
			blade: { base: 8, exp: 0 },
			dagger: { base: 4, exp: 0 },
			spear: { base: 5, exp: 0 },
			axe: { base: 10, exp: 0 },
			mace: { base: 6, exp: 0 },
			shield: { base: 7, exp: 0 },
			bow: { base: 3, exp: 0 },
			magicWand: { base: 0, exp: 0 },
			staff: { base: 0, exp: 0 },
			tome: { base: 0, exp: 0 },
			orb: { base: 0, exp: 0 },
		},
		battlers: {
			pATK: { base: 0, exp: 0 },
			pHIT: { base: 0, exp: 0 },
			pCRT: { base: 0, exp: 0 },
			pDEF: { base: 0, exp: 0 },
			mATK: { base: 0, exp: 0 },
			mHIT: { base: 0, exp: 0 },
			mCRT: { base: 0, exp: 0 },
			mDEF: { base: 0, exp: 0 },
			chiWarmATK: { base: 0, exp: 0 },
			chiColdATK: { base: 0, exp: 0 },
			chiWarmDEF: { base: 0, exp: 0 },
			chiColdDEF: { base: 0, exp: 0 },
			slash: { base: 0, exp: 0 },
			pierce: { base: 0, exp: 0 },
			blunt: { base: 0, exp: 0 },
			slashDEF: { base: 18, exp: 0 },
    		pierceDEF: { base: 15, exp: 0 },
    		bluntDEF: { base: 17, exp: 0 },
			dodge: { base: 0, exp: 0 },
			orderATK: {
                base: 0,
                exp: 0
            },
            chaosATK: {
                base: 0,
                exp: 0
            },
            geoATK: {
                base: 0,
                exp: 0
            },
            waterATK: {
                base: 0,
                exp: 0
            },
            airATK: {
                base: 0,
                exp: 0
            },
            fireATK: {
                base: 0,
                exp: 0
            },
            orderDEF: {
                base: 0,
                exp: 0
            },
            chaosDEF: {
                base: 0,
                exp: 0
            },
            geoDEF: {
                base: 0,
                exp: 0
            },
            waterDEF: {
                base: 0,
                exp: 0
            },
            airDEF: {
                base: 0,
                exp: 0
            },
            fireDEF: {
                base: 0,
                exp: 0
            }
		},
		elements: {
			order: { base: 0, exp: 0 },
			chaos: { base: 0, exp: 0 },
			geo: { base: 0, exp: 0 },
			water: { base: 0, exp: 0 },
			air: { base: 0, exp: 0 },
			fire: { base: 0, exp: 0 },
		},
		artisans: {
			mining: { base: 0, exp: 0 },
			smithing: { base: 0, exp: 0 },
			woodcutting: { base: 0, exp: 0 },
			carpentry: { base: 0, exp: 0 },
			foraging: { base: 0, exp: 0 },
			weaving: { base: 0, exp: 0 },
			skinning: { base: 0, exp: 0 },
			tanning: { base: 0, exp: 0 },
			jewelry: { base: 0, exp: 0 },
			alchemy: { base: 0, exp: 0 },
			cooking: { base: 0, exp: 0 },
			enchanting: { base: 0, exp: 0 },
		},
		equipments: {
			mainHand: GearSeedWeaponEnum.IronGreatAxe,
			offHand: null,
			armor: GearSeedArmorEnum.armor_medium_chainmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits: [],
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_cleave, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierBarbarian,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_bow_m,
		level: 5,
		portrait: "orc_bow_m",
		race: RaceEnum.ORC,
		background: "An orc archer",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.RecurveBow,
			offHand: null,
			armor: GearSeedArmorEnum.armor_light_leather,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [{ skillID: SkillEnum.skill_power_shot, level: 5, exp: 0 }],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierRanger,
	}),
	new CharacterArchetype({
		name: "Orc",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_bow_f,
		level: 5,
		portrait: "orc_bow_f",
		race: RaceEnum.ORC,
		background: "An orc archer",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.RecurveBow,
			offHand: null,
			armor: GearSeedArmorEnum.armor_light_leather,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_double_strafe, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierRanger,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_wand_m,
		level: 5,
		portrait: "orc_wand_m",
		race: RaceEnum.ORC,
		background: "An orc cleric",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.MagicWand,
			offHand: null,
			armor: GearSeedArmorEnum.armor_light_leather,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_heal, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_bless, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierCleric,
	}),
	new CharacterArchetype({
		name: "Orc",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_wand_f,
		level: 5,
		portrait: "orc_wand_f",
		race: RaceEnum.ORC,
		background: "An orc warlock",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.MagicWand,
			offHand: null,
			armor: GearSeedArmorEnum.armor_light_hide,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_heal, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_bless, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierCleric,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_staff_m,
		level: 5,
		portrait: "orc_staff_m",
		race: RaceEnum.ORC,
		background: "An orc wizard",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.EnchantedMagicStaff,
			offHand: null,
			armor: GearSeedArmorEnum.armor_light_hide,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_fire_ball, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_arcane_explosion, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierMage,
	}),

	new CharacterArchetype({
		name: "Orc",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_staff_f,
		level: 5,
		portrait: "orc_staff_f",
		race: RaceEnum.ORC,
		background: "An orc wizard",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 70,
		energy: 100,
		fame: 0,
		gold: 0,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.EnchantedMagicStaff,
			offHand: null,
			armor: GearSeedArmorEnum.armor_light_hide,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits,
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_fire_ball, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_ice_nova, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierMage,
	}),

	new CharacterArchetype({
		name: "Orc Chieftain",
		gender: "male",
		type: CharacterType.humanoid,
		id: OrcID.orc_chieftain_warrior_m,
		level: 10,
		portrait: "orc_chieftain_warrior_m",
		race: RaceEnum.ORC,
		background: "An orc chieftain warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 80,
		energy: 120,
		fame: 50,
		gold: 100,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.SteelShepherdAxe,
			offHand: GearSeedWeaponEnum.IronRoundShield,
			armor: GearSeedArmorEnum.armor_heavy_bandedmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits: [],
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_roar, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierChieftain,
	}),
	new CharacterArchetype({
		name: "Orc Chieftain",
		gender: "female",
		type: CharacterType.humanoid,
		id: OrcID.orc_chieftain_warrior_f,
		level: 10,
		portrait: "orc_chieftain_warrior_f",
		race: RaceEnum.ORC,
		background: "An orc chieftain warrior",
		alignment: { good: 0, evil: 0, law: 0, chaos: 10 },
		mood: 80,
		energy: 120,
		fame: 50,
		gold: 100,
		exp: 0,
		isDead: false,
		lastTarget: "",
		attributes,
		proficiencies,
		battlers,
		elements,
		artisans,
		equipments: {
			mainHand: GearSeedWeaponEnum.SteelShepherdAxe,
			offHand: GearSeedWeaponEnum.IronRoundShield,
			armor: GearSeedArmorEnum.armor_heavy_bandedmail,
			necklace: null,
			ring: null,
			cloth: null,
			headWear: null,
		},
		internals: [],
		activeInternal: null,
		traits: [],
		skills: [],
		activeSkills: [
			{ skillID: SkillEnum.skill_power_strike, level: 5, exp: 0 },
			{ skillID: SkillEnum.skill_roar, level: 5, exp: 0 },
		],
		itemsBag: [],
		baseAC: 5,
		location: "Orc Camp",
		isSummoned: false,
		arcaneAptitude: 80,
		classModifier: classModifierChieftain,
	}),
];
