export enum CharacterStatusEnum {
    none = "none",
    // Attributes
    charisma = "charisma",
    luck = "luck",
    intelligence = "intelligence",
    leadership = "leadership",
    vitality = "vitality",
    willpower = "willpower",
    breath = "breath",
    planar = "planar",
    dexterity = "dexterity",
    agility = "agility",
    strength = "strength",
    endurance = "endurance",

    // Proficiencies
    bareHand = "bareHand",
    sword = "sword",
    blade = "blade",
    dagger = "dagger",
    spear = "spear",
    mace = "mace",
    axe = "axe",
    shield = "shield",
    bow = "bow",
    magicWand = "magicWand",
    staff = "staff",
    tome = "tome",
    orb = "orb",

    // Battlers
    pATK = "pATK",
    pHIT = "pHIT",
    pCRT = "pCRT",
    pDEF = "pDEF",
    slash = "slash",
    pierce = "pierce",
    blunt = "blunt",
    slashDEF = "slashDEF",
    pierceDEF = "pierceDEF",
    bluntDEF = "bluntDEF",
    mATK = "mATK",
    mHIT = "mHIT",
    mCRT = "mCRT",
    mDEF = "mDEF",
    chiWarmATK = "chiWarmATK",
    chiColdATK = "chiColdATK",
    chiWarmDEF = "chiWarmDEF",
    chiColdDEF = "chiColdDEF",
    dodge = "dodge",

    // Elements
    order = "order",
    chaos = "chaos",
    geo = "geo",
    water = "water",
    air = "air",
    fire = "fire",

    // New Artisans fields
    mining = 'mining',
    smithing = 'smithing',
    woodcutting = 'woodcutting',
    carpentry = 'carpentry',
    foraging = 'foraging',
    weaving = 'weaving',
    skinning = 'skinning',
    tanning = 'tanning',
    jewelry = 'jewelry',
    cooking = 'cooking',
    alchemy = 'alchemy',
    enchanting = 'enchanting',
}