export class PassiveStatusBonus {
    attributes? : {
        charisma?: number | null,
        luck?: number | null,
        intelligence?: number | null,
        leadership?: number | null,
        vitality?: number | null,
        willpower?: number | null,
        breath?: number | null,
        planar?: number | null,
        dexterity?: number | null,
        agility?: number | null,
        strength?: number | null,
        endurance?: number | null
    }
    proficiencies? : {
        bareHand?: number | null,
        sword?: number | null,
        blade?: number | null,
        spear?: number | null,
        axe?: number | null,
        bow?: number | null,
        dagger?: number | null,
        magicWand?: number | null,
        staff?: number | null,
        tome?: number | null,
        orb?: number | null,
        mace?: number | null,
        shield?: number | null
    }
    artisans?: {
        mining? : number | null,
        smithing? : number | null,
        woodcutting? : number | null,
        carpentry? : number | null,
        foraging? : number | null,
        weaving? : number | null,
        skinning? : number | null,
        tanning? : number | null,
        jewelry? : number | null,
        alchemy?: number | null,
        cooking?: number | null,
        enchanting?: number | null
    }
    battlers? : {
        pATK?: number | null,
        pHIT?: number | null,
        pDEF?: number | null,
        pCRT?: number | null,
        mATK?: number | null,
        mHIT?: number | null,
        mDEF?: number | null,
        mCRT?: number | null,
        chiWarmATK?: number | null,
        chiWarmDEF?: number | null,
        chiColdATK?: number | null,
        chiColdDEF?: number | null,
        dodge?: number | null
    }
    elements? : {
        order?: number | null,
        chaos?: number | null,
        geo?: number | null,
        water?: number | null,
        air?: number | null,
        fire?: number | null
    }
    constructor({
        charisma = null,
        luck = null,
        intelligence = null,
        leadership = null,
        vitality = null,
        willpower = null,
        breath = null,
        planar = null,
        dexterity = null,
        agility = null,
        strength = null,
        endurance = null,
        bareHand = null,
        sword = null,
        blade = null,
        spear = null,
        axe = null,
        bow = null,
        dagger = null,
        magicWand = null,
        staff = null,
        tome = null,
        orb = null,
        mace = null,
        shield = null,
        mining = null,
        smithing = null,
        woodcutting = null,
        carpentry = null,
        foraging = null,
        weaving = null,
        skinning = null,
        tanning = null,
        jewelry = null,
        alchemy = null,
        cooking = null,
        enchanting = null,
        pATK = null,
        pHIT = null,
        pDEF = null,
        pCRT = null,
        mATK = null,
        mHIT = null,
        mDEF = null,
        mCRT = null,
        chiWarmATK = null,
        chiWarmDEF = null,
        chiColdATK = null,
        chiColdDEF = null,
        dodge = null,
        order = null,
        chaos = null,
        geo = null,
        water = null,
        air = null,
        fire = null
    }: {
        charisma?: number | null,
        luck?: number | null,
        intelligence?: number | null,
        leadership?: number | null,
        vitality?: number | null,
        willpower?: number | null,
        breath?: number | null,
        planar?: number | null,
        dexterity?: number | null,
        agility?: number | null,
        strength?: number | null,
        endurance?: number | null,
        bareHand?: number | null,
        sword?: number | null,
        blade?: number | null,
        spear?: number | null,
        axe?: number | null,
        bow?: number | null,
        dagger?: number | null,
        magicWand?: number | null,
        staff?: number | null,
        tome?: number | null,
        orb?: number | null,
        mace?: number | null,
        shield?: number | null,
        mining?: number | null,
        smithing?: number | null,
        woodcutting?: number | null,
        carpentry?: number | null,
        foraging?: number | null,
        weaving?: number | null,
        skinning?: number | null,
        tanning?: number | null,
        jewelry?: number | null,
        alchemy?: number | null,
        cooking?: number | null,
        enchanting?: number | null,
        pATK?: number | null,
        pHIT?: number | null,
        pDEF?: number | null,
        pCRT?: number | null,
        mATK?: number | null,
        mHIT?: number | null,
        mDEF?: number | null,
        mCRT?: number | null,
        chiWarmATK?: number | null,
        chiWarmDEF?: number | null,
        chiColdATK?: number | null,
        chiColdDEF?: number | null,
        dodge?: number | null,
        order?: number | null,
        chaos?: number | null,
        geo?: number | null,
        water?: number | null,
        air?: number | null,
        fire?: number | null
    }){
        this.attributes = {
            charisma,
            luck,
            intelligence,
            leadership,
            vitality,
            willpower,
            breath,
            planar,
            dexterity,
            agility,
            strength,
            endurance
        }
        this.proficiencies = {
            bareHand,
            sword,
            blade,
            spear,
            axe,
            bow,
            dagger,
            magicWand,
            staff,
            tome,
            orb,
            mace,
            shield
        }
        this.artisans = {
            mining,
            smithing,
            woodcutting,
            carpentry,
            foraging,
            weaving,
            skinning,
            tanning,
            jewelry,
            alchemy,
            cooking,
            enchanting
        }
        this.battlers = {
            pATK,
            pHIT,
            pDEF,
            pCRT,
            mATK,
            mHIT,
            mDEF,
            mCRT,
            chiWarmATK,
            chiWarmDEF,
            chiColdATK,
            chiColdDEF,
            dodge
        }
        this.elements = {
            order,
            chaos,
            geo,
            water,
            air,
            fire
        }
    }
}