export enum CharacterStatusEnum {
    none = "none",
    // Attributes
    charisma = "charisma",
    luck = "luck",
    intelligence = "intelligence",
    leadership = "leadership",
    vitality = "vitality",
    willpower = "willpower",
    breath = "breath",
    planar = "planar",
    dexterity = "dexterity",
    agility = "agility",
    strength = "strength",
    endurance = "endurance",

    // สเน่ห์ = 'สเน่ห์',
    // โชค = 'โชค',
    // ปัญญา = 'ปัญญา',
    // ผู้นำ = 'ผู้นำ',
    // สุขภาพ = 'สุขภาพ',
    // จิตใจ  = 'จิตใจ',
    // ลมปราณ = 'ลมปราณ',
    // อาคม = 'อาคม',
    // สมดุลย์ = 'สมดุลย์',
    // ว่องไว  = 'ว่องไว',
    // กล้ามเนื้อ = 'กล้ามเนื้อ',
    // อดทน = 'อดทน',

    // Proficiencies
    bareHand = "bareHand",
    sword = "sword",
    blade = "blade",
    dagger = "dagger",
    spear = "spear",
    mace = "mace",
    axe = "axe",
    shield = "shield",
    bow = "bow",
    magicWand = "magicWand",
    staff = "staff",
    tome = "tome",
    orb = "orb",

    // มือเปล่า = 'มือเปล่า',
    // กระบี่ = 'กระบี่',
    // ดาบ = 'ดาบ',
    // มีดสั้น = 'มีดสั้น',
    // หอก = 'หอก',
    // ฆ้อน = 'ฆ้อน',
    // ขวาน = 'ขวาน',
    // โล่ = 'โล่',
    // ธนู = 'ธนู',
    // คทา = 'คทา',
    // ไม้เท้า = 'ไม้เท้า',
    // ตำรา = 'ตำรา',
    // ลูกแก้ว = 'ลูกแก้ว',

    // Battlers
    pATK = "pATK",
    pHIT = "pHIT",
    pCRT = "pCRT",
    pDEF = "pDEF",
    slash = "slash",
    pierce = "pierce",
    blunt = "blunt",
    slashDEF = "slashDEF",
    pierceDEF = "pierceDEF",
    bluntDEF = "bluntDEF",
    mATK = "mATK",
    mHIT = "mHIT",
    mCRT = "mCRT",
    mDEF = "mDEF",
    chiWarmATK = "chiWarmATK",
    chiColdATK = "chiColdATK",
    chiWarmDEF = "chiWarmDEF",
    chiColdDEF = "chiColdDEF",
    dodge = "dodge",

    // โจมตีกายภาพ = 'โจมตีกายภาพ',
    // แม่นยำกายภาพ = 'แม่นยำกายภาพ',
    // คริติคอลกายภาพ = 'คริติคอลกายภาพ',
    // ป้องกันกายภาพ = 'ป้องกันกายภาพ',
    // ฟัน = 'ฟัน',
    // แทง = 'แทง',
    // ทุบ = 'ทุบ',
    // โจมตีเวทย์ = 'โจมตีเวทย์',
    // แม่นยำเวทย์ = 'แม่นยำเวทย์',
    // คริติคอลเวทย์ = 'คริติคอลเวทย์',
    // ป้องกันเวทย์ = 'ป้องกันเวทย์',
    // โจมตีภายในร้อน = 'โจมตีภายในร้อน',
    // โจมตีภายในเย็น = 'โจมตีภายในเย็น',
    // ป้องกันภายในร้อน = 'ป้องกันภายในร้อน',
    // ป้องกันภายในเย็น = 'ป้องกันภายในเย็น',
    // หลบหลีก = 'หลบหลีก',

    // Elements
    order = "order",
    chaos = "chaos",
    geo = "geo",
    water = "water",
    air = "air",
    fire = "fire",

    // ระเบียบ = 'ระเบียบ',
    // ยุ่งเหยิง = 'ยุ่งเหยิง',
    // ดิน = 'ดิน',
    // น้ำ = 'น้ำ',
    // ลม = 'ลม',
    // ไฟ = 'ไฟ',

    // Artisans
    // tailoring = "tailoring",
    // leatherWorking = "leatherWorking",
    // smithing = "smithing",
    // woodWorking = "woodWorking",
    // jewelCrafting = "jewelCrafting",
    // alchemy = "alchemy",
    // cooking = "cooking",
    // enchanting = "enchanting"

    // New Artisans fields
    mining = 'mining',
    smithing = 'smithing',
    woodcutting = 'woodcutting',
    carpentry = 'carpentry',
    foraging = 'foraging',
    weaving = 'weaving',
    skinning = 'skinning',
    tanning = 'tanning',
    jewelry = 'jewelry',
    cooking = 'cooking',
    alchemy = 'alchemy',
    enchanting = 'enchanting',

    // เหมือง = 'เหมือง',
    // ตีเหล็ก = 'ตีเหล็ก',
    // ตัดไม้ = 'ตัดไม้',
    // งานไม้ = 'งานไม้',
    // สำรวจ = 'สำรวจ',
    // ทอผ้า = 'ทอผ้า',
    // นักล่าสัตว์ = 'นักล่าสัตว์',
    // ทำหนัง = 'ทำหนัง',
    // ช่างเพชร = 'ช่างเพชร',
    // ทำอาหาร = 'ทำอาหาร',
    // ทำยา = 'ทำยา',
    // ลงอาคม  = 'ลงอาคม',
}