export enum ElementTypes {
    order = "order",
    chaos = "chaos",
    geo = "geo",
    water = "water",
    air = "air",
    fire = "fire",
    ice = "ice",
    spirit = "spirit",
    lightning = "lightning",
    demonic = "demonic",
    metal = "metal",
    angelic = "angelic",
    nature = "nature",
    life = "life",
    dark = "dark",
    necrotic = "necrotic",
    poison = "poison",
    holy = "holy",
    arcane = "arcane",
    resource = "resource",
    chiWarm = "chiWarm",
    chiCold = "chiCold",
    chiHarmony = "chiHarmony",
    none = "none",
}

export enum FundamentalElementTypes {
    order = "order",
    chaos = "chaos",
    geo = "geo",
    water = "water",
    air = "air",
    fire = "fire",
    none = "none",
}