// import { ConsumableEffect } from "../../../../Common/Enums/Item/ConsumableEffect";
// import { Tier } from "../../../Utility/Tier";
// import { createTableIfNotExists } from "../../Seeding";

// export class ItemConsumableArchetype {
//     id!: string;
//     name!: string;
//     description!: string;
// 	type!: ConsumableType;
//     image!: string;
//     cost!: number;
//     weight!: number;
//     tier!: Tier;
//     effects!: ConsumableEffect[];
//     consumedAfterUse!: boolean;
//     constructor(dto: {
//         id: string;
//         name: string;
//         description: string;
// 	    type: ConsumableType;
//         image: string;
//         cost: number;
//         weight: number;
//         tier: Tier;
//         effects: ConsumableEffect[];
//         consumedAfterUse: boolean;
//     }) {
//         Object.assign(this, dto);
//     }
// }


// export enum ItemConsumableEnum {
//     // Common
//     // food
//     breadLoaf = "itemConsumable_breadLoaf",
//     heartyStew = "itemConsumable_heartyStew",
//     roastedMushrooms = "itemConsumable_roastedMushrooms",
//     appleTart = "itemConsumable_appleTart",
//     smokedFish = "itemConsumable_smokedFish",
//     grilledVegetables = "itemConsumable_grilledVegetables",
//     cheeseWheel = "itemConsumable_cheeseWheel",
//     sausageLinks = "itemConsumable_sausageLinks",
//     roastedChicken = "itemConsumable_roastedChicken",
//     fruitPlatter = "itemConsumable_fruitPlatter",
//     meatPie = "itemConsumable_meatPie",
//     honeyBread = "itemConsumable_honeyBread",
//     berryPastry = "itemConsumable_berryPastry",
//     vegetableSoup = "itemConsumable_vegetableSoup",
//     spicedPotatoes = "itemConsumable_spicedPotatoes",
//     // drink
//     herbalTea = "itemConsumable_herbalTea",
//     freshSpringWater = "itemConsumable_freshSpringWater",
//     sweetBerryJuice = "itemConsumable_sweetBerryJuice",
//     spicedAle = "itemConsumable_spicedAle",
//     milk = "itemConsumable_milk",
//     // potion
//     basicHealingPotion = "itemConsumable_basicHealingPotion",
//     energyTonic = "itemConsumable_energyTonic",
//     calmingDraught = "itemConsumable_calmingDraught",
//     minorManaPotion = "itemConsumable_minorManaPotion",
//     basicAntidote = "itemConsumable_basicAntidote",
//     // salve
//     soothingBalm = "itemConsumable_soothingBalm",
//     herbalWoundSalve = "itemConsumable_herbalWoundSalve",

//     // Uncommon
//     // food
//     spicedLambChops = "itemConsumable_spicedLambChops",
//     glazedPheasant = "itemConsumable_glazedPheasant",
//     dragonfruitSalad = "itemConsumable_dragonfruitSalad",
//     caramelizedOnionTart = "itemConsumable_caramelizedOnionTart",
//     grilledSalmon = "itemConsumable_grilledSalmon",
//     butteredCrabClaws = "itemConsumable_butteredCrabClaws",
//     mushroomRisotto = "itemConsumable_mushroomRisotto",
//     smokedVenison = "itemConsumable_smokedVenison",
//     wildBoarSteak = "itemConsumable_wildBoarSteak",
//     stuffedBellPeppers = "itemConsumable_stuffedBellPeppers",
//     goldenBerryTart = "itemConsumable_goldenBerryTart",
//     candiedNuts = "itemConsumable_candiedNuts",
//     roastedHerbPotatoes = "itemConsumable_roastedHerbPotatoes",
//     honeyGlazedDuck = "itemConsumable_honeyGlazedDuck",
//     citrusCuredHam = "itemConsumable_citrusCuredHam",
//     // drink
//     elvenWine = "itemConsumable_elvenWine",
//     dwarvenStout = "itemConsumable_dwarvenStout",
//     spicedMulledWine = "itemConsumable_spicedMulledWine",
//     enchantedSpringWater = "itemConsumable_enchantedSpringWater",
//     sparklingCitrusJuice = "itemConsumable_sparklingCitrusJuice",
//     // potion
//     strongHealingPotion = "itemConsumable_strongHealingPotion",
//     energyElixir = "itemConsumable_energyElixir",
//     focusTonic = "itemConsumable_focusTonic",
//     manaElixir = "itemConsumable_manaElixir",
//     antidoteBrew = "itemConsumable_antidoteBrew",
//     // salve
//     rejuvenatingSalve = "itemConsumable_rejuvenatingSalve",
//     fireResistantOintment = "itemConsumable_fireResistantOintment",

//     // Rare
//     // food
//     phoenixEggOmelette = "itemConsumable_phoenixEggOmelette",
//     truffleSteak = "itemConsumable_truffleSteak",
//     starfruitSorbet = "itemConsumable_starfruitSorbet",
//     enchantedPumpkinPie = "itemConsumable_enchantedPumpkinPie",
//     celestialLambRoast = "itemConsumable_celestialLambRoast",
//     emberGrilledEel = "itemConsumable_emberGrilledEel",
//     frostLotusSalad = "itemConsumable_frostLotusSalad",
//     dragonTailStew = "itemConsumable_dragonTailStew",
//     lavaSpiceCrab = "itemConsumable_lavaSpiceCrab",
//     silverleafSalmon = "itemConsumable_silverleafSalmon",
//     // drink
//     sunfireAle = "itemConsumable_sunfireAle",
//     moonlightTea = "itemConsumable_moonlightTea",
//     frozenWine = "itemConsumable_frozenWine",
//     mysticElixir = "itemConsumable_mysticElixir",
//     arcaneBrew = "itemConsumable_arcaneBrew",
//     // potion
//     elixirOfThePhoenix = "itemConsumable_elixirOfThePhoenix",
//     manaRegenerationPotion = "itemConsumable_manaRegenerationPotion",
//     giantStrengthPotion = "itemConsumable_giantStrengthPotion",
//     stormEssencePotion = "itemConsumable_stormEssencePotion",
//     shadowVeilPotion = "itemConsumable_shadowVeilPotion",
//     // salve
//     ethericHealingSalve = "itemConsumable_ethericHealingSalve",
//     shadowGuardSalve = "itemConsumable_shadowGuardSalve",
//     // oil
//     dragonOil = "itemConsumable_dragonOil",
//     frostbiteOil = "itemConsumable_frostbiteOil",
//     // coatingSolution
//     arcaneResonanceCoating = "itemConsumable_arcaneResonanceCoating",
//     solarflareCoating = "itemConsumable_solarflareCoating",
//     // rune
//     runeOfFortitude = "itemConsumable_runeOfFortitude",
//     runeOfTheStorm = "itemConsumable_runeOfTheStorm",
//     // powder
//     elementalPowder = "itemConsumable_elementalPowder",
//     astralDust = "itemConsumable_astralDust",

//     // Epic
//     // food
//     celestialFruitSalad = "itemConsumable_celestialFruitSalad",
//     leviathanSteak = "itemConsumable_leviathanSteak",
//     draconicSpicePlatter = "itemConsumable_draconicSpicePlatter",
//     // drink
//     etherealElixir = "itemConsumable_etherealElixir",
//     voidwine = "itemConsumable_voidwine",
//     // potion
//     soulfirePotion = "itemConsumable_soulfirePotion",
//     starryNightDraught = "itemConsumable_starryNightDraught",
//     chiHarmonyElixir = "itemConsumable_chiHarmonyElixir",
//     grandArcanePotion = "itemConsumable_grandArcanePotion",
//     // salve
//     divineHealingBalm = "itemConsumable_divineHealingBalm",
//     abyssalSalve = "itemConsumable_abyssalSalve",
//     // oil
//     celestialBladeOil = "itemConsumable_celestialBladeOil",
//     infernoOil = "itemConsumable_infernoOil",
//     // coatingSolution
//     phoenixWingCoating = "itemConsumable_phoenixWingCoating",
//     froststormCoating = "itemConsumable_froststormCoating",
//     // rune
//     runeOfTranscendence = "itemConsumable_runeOfTranscendence",
//     runeOfTheVoid = "itemConsumable_runeOfTheVoid",
//     // powder
//     essenceOfDragonscale = "itemConsumable_essenceOfDragonscale",
//     celestialGlowPowder = "itemConsumable_celestialGlowPowder",

//     // Legendary
//     // food
//     ambrosiaFeast = "itemConsumable_ambrosiaFeast",
//     worldTreeFruit = "itemConsumable_worldTreeFruit",
//     // drink
//     draughtOfImmortality = "itemConsumable_draughtOfImmortality",
//     elixirOfTheSun = "itemConsumable_elixirOfTheSun",
//     // potion
//     dragonHeartElixir = "itemConsumable_dragonHeartElixir",
//     essenceOfLight = "itemConsumable_essenceOfLight",
//     celestialManaElixir = "itemConsumable_celestialManaElixir",
//     // salve
//     phoenixAshSalve = "itemConsumable_phoenixAshSalve",
//     eternalBloomBalm = "itemConsumable_eternalBloomBalm",
//     // oil
//     orichalcumWeaponOil = "itemConsumable_orichalcumWeaponOil",
//     starlightOil = "itemConsumable_starlightOil",
//     // coatingSolution
//     netherVoidCoating = "itemConsumable_netherVoidCoating",
//     lightweaverCoating = "itemConsumable_lightweaverCoating",
//     // rune
//     runeOfAscension = "itemConsumable_runeOfAscension",
//     runeOfTheEternalFlame = "itemConsumable_runeOfTheEternalFlame",
//     // powder
//     powderedDragonBone = "itemConsumable_powderedDragonBone",
//     essenceOfTheStars = "itemConsumable_essenceOfTheStars",

//     // Unique
//     // potion
//     voidEssenceElixir = "itemConsumable_voidEssenceElixir",
//     oracleGemPotion = "itemConsumable_oracleGemPotion",
//     abyssalShardBrew = "itemConsumable_abyssalShardBrew",
//     titanstoneTonic = "itemConsumable_titanstoneTonic",
//     // salve
//     soulBindingSalve = "itemConsumable_soulBindingSalve",
//     // oil
//     titanstoneOil = "itemConsumable_titanstoneOil",
//     spiritwoodOil = "itemConsumable_spiritwoodOil",
//     // coatingSolution
//     heartwoodCoating = "itemConsumable_heartwoodCoating",
//     timeweaverSilkCoating = "itemConsumable_timeweaverSilkCoating",
//     // rune
//     runeOfEternalHarmony = "itemConsumable_runeOfEternalHarmony",
//     // powder
//     abyssWeavePowder = "itemConsumable_abyssWeavePowder",
//     oracleGemDust = "itemConsumable_oracleGemDust",

//     // Divine
//     // food
//     ambrosiaSoup = "itemConsumable_ambrosiaSoup",
//     // potion
//     godsbloodPotion = "itemConsumable_godsbloodPotion",
//     essenceOfEternity = "itemConsumable_essenceOfEternity",
//     celestialTearsPotion = "itemConsumable_celestialTearsPotion",
//     // salve
//     galaxyDustSalve = "itemConsumable_galaxyDustSalve",
//     // coatingSolution
//     aetheriumCoating = "itemConsumable_aetheriumCoating",
//     // rune
//     runeOfAether = "itemConsumable_runeOfAether",
//     // powder
//     stardustPowder = "itemConsumable_stardustPowder",
// }


// export const ItemConsumableSeed: ItemConsumableArchetype[] = [
//     // MARK: Common
// 	// Common Food
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.breadLoaf,
// 		name: "Bread Loaf",
// 		description: "A simple loaf of bread, commonly found in taverns and bakeries.",
// 		type: ConsumableType.food,
// 		image: "/images/items/breadLoaf.png",
// 		cost: 5, // Higher than basic wheat due to crafting
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0, // No lasting effect
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.heartyStew,
// 		name: "Hearty Stew",
// 		description: "A rich stew, packed with meat and vegetables. Restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/heartyStew.png",
// 		cost: 8,
// 		weight: 2,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.roastedMushrooms,
// 		name: "Roasted Mushrooms",
// 		description: "A plate of lightly seasoned, roasted mushrooms, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/roastedMushrooms.png",
// 		cost: 6,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 8,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.appleTart,
// 		name: "Apple Tart",
// 		description: "A sweet apple tart, restores stamina and grants a small charisma boost.",
// 		type: ConsumableType.food,
// 		image: "/images/items/appleTart.png",
// 		cost: 7,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.charisma],
// 		baseEffectMagnitude: 5,
// 		baseEffectDuration: 2,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.smokedFish,
// 		name: "Smoked Fish",
// 		description: "A savory smoked fish, restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/smokedFish.png",
// 		cost: 9,
// 		weight: 1.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 12,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.grilledVegetables,
// 		name: "Grilled Vegetables",
// 		description: "A plate of seasoned grilled vegetables, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/grilledVegetables.png",
// 		cost: 5,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 8,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.cheeseWheel,
// 		name: "Cheese Wheel",
// 		description: "A large wheel of cheese, restores stamina and grants a small vitality boost.",
// 		type: ConsumableType.food,
// 		image: "/images/items/cheeseWheel.png",
// 		cost: 10,
// 		weight: 3,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 4,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.sausageLinks,
// 		name: "Sausage Links",
// 		description: "A string of sausages, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/sausageLinks.png",
// 		cost: 6,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.roastedChicken,
// 		name: "Roasted Chicken",
// 		description: "A full roasted chicken, restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/roastedChicken.png",
// 		cost: 12,
// 		weight: 2,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 20,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.fruitPlatter,
// 		name: "Fruit Platter",
// 		description: "An assortment of fresh fruits, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/fruitPlatter.png",
// 		cost: 7,
// 		weight: 1.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.meatPie,
// 		name: "Meat Pie",
// 		description: "A hearty meat pie, restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/meatPie.png",
// 		cost: 9,
// 		weight: 1.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.honeyBread,
// 		name: "Honey Bread",
// 		description: "A sweet and filling honey bread, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/honeyBread.png",
// 		cost: 7,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.berryPastry,
// 		name: "Berry Pastry",
// 		description: "A delicate pastry filled with berries, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/berryPastry.png",
// 		cost: 6,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 9,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.vegetableSoup,
// 		name: "Vegetable Soup",
// 		description: "A warm bowl of vegetable soup, restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/vegetableSoup.png",
// 		cost: 5,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 8,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.spicedPotatoes,
// 		name: "Spiced Potatoes",
// 		description: "A plate of spiced potatoes, restores stamina and boosts vitality temporarily.",
// 		type: ConsumableType.food,
// 		image: "/images/items/spicedPotatoes.png",
// 		cost: 7,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 5,
// 		baseEffectDuration: 4,
// 		consumedAfterUse: true,
// 	}),

// 	// Common Drink
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.herbalTea,
// 		name: "Herbal Tea",
// 		description: "A calming herbal tea, restores stamina and relieves stress.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/herbalTea.png",
// 		cost: 6,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.willpower],
// 		baseEffectMagnitude: 5,
// 		baseEffectDuration: 2,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.freshSpringWater,
// 		name: "Fresh Spring Water",
// 		description: "A bottle of fresh spring water, restores stamina.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/freshSpringWater.png",
// 		cost: 5,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 7,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.sweetBerryJuice,
// 		name: "Sweet Berry Juice",
// 		description: "A refreshing glass of berry juice, restores stamina.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/sweetBerryJuice.png",
// 		cost: 6,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 8,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.spicedAle,
// 		name: "Spiced Ale",
// 		description: "A glass of spiced ale, restores stamina and boosts vitality temporarily.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/spicedAle.png",
// 		cost: 7,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 5,
// 		baseEffectDuration: 4,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.milk,
// 		name: "Milk",
// 		description: "A fresh glass of milk, restores stamina.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/milk.png",
// 		cost: 5,
// 		weight: 1,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 7,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),

// 	// Common Potions
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.basicHealingPotion,
// 		name: "Basic Healing Potion",
// 		description: "A simple potion that restores health.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/basicHealingPotion.png",
// 		cost: 10,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 25,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.energyTonic,
// 		name: "Energy Tonic",
// 		description: "A tonic that boosts stamina and vitality temporarily.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/energyTonic.png",
// 		cost: 12,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.calmingDraught,
// 		name: "Calming Draught",
// 		description: "A potion that restores willpower and relieves stress.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/calmingDraught.png",
// 		cost: 8,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.willpower],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 4,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.minorManaPotion,
// 		name: "Minor Mana Potion",
// 		description: "A basic potion that restores a small amount of mana.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/minorManaPotion.png",
// 		cost: 9,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.resportMana],
// 		baseEffectMagnitude: 20,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.basicAntidote,
// 		name: "Basic Antidote",
// 		description: "A potion that cures basic poisons and toxins.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/basicAntidote.png",
// 		cost: 7,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),

// 	// Common Salves
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.soothingBalm,
// 		name: "Soothing Balm",
// 		description: "A balm that soothes pain and restores health over time.",
// 		type: ConsumableType.salve,
// 		image: "/images/items/soothingBalm.png",
// 		cost: 6,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.regenerateHealth],
// 		baseEffectMagnitude: 5,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.herbalWoundSalve,
// 		name: "Herbal Wound Salve",
// 		description: "A salve that helps wounds heal faster over time.",
// 		type: ConsumableType.salve,
// 		image: "/images/items/herbalWoundSalve.png",
// 		cost: 7,
// 		weight: 0.5,
// 		tier: Tier.common,
// 		effects: [ConsumableEffect.regenerateHealth],
// 		baseEffectMagnitude: 7,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),

//     // MARK: Uncommon
//     // Uncommon Food
//     new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.spicedLambChops,
// 		name: "Spiced Lamb Chops",
// 		description: "A plate of succulent lamb chops seasoned with exotic spices. Restores stamina and boosts vitality.",
// 		type: ConsumableType.food,
// 		image: "/images/items/spicedLambChops.png",
// 		cost: 60,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 20,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.glazedPheasant,
// 		name: "Glazed Pheasant",
// 		description: "A roasted pheasant glazed with honey and herbs. Restores health and stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/glazedPheasant.png",
// 		cost: 66,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreHealth, ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 25,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.dragonfruitSalad,
// 		name: "Dragonfruit Salad",
// 		description: "A vibrant salad made from rare dragonfruit, boosting health and charisma.",
// 		type: ConsumableType.food,
// 		image: "/images/items/dragonfruitSalad.png",
// 		cost: 55,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreHealth, ConsumableEffect.charisma],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 8,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.caramelizedOnionTart,
// 		name: "Caramelized Onion Tart",
// 		description: "A sweet and savory tart topped with caramelized onions. Restores stamina and grants temporary intelligence.",
// 		type: ConsumableType.food,
// 		image: "/images/items/caramelizedOnionTart.png",
// 		cost: 50,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.intelligence],
// 		baseEffectMagnitude: 12,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.grilledSalmon,
// 		name: "Grilled Salmon",
// 		description: "A perfectly grilled salmon fillet, rich in flavor. Restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/grilledSalmon.png",
// 		cost: 63,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 20,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.butteredCrabClaws,
// 		name: "Buttered Crab Claws",
// 		description: "Delicious crab claws drenched in butter. Restores stamina and boosts dexterity temporarily.",
// 		type: ConsumableType.food,
// 		image: "/images/items/butteredCrabClaws.png",
// 		cost: 70,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.dexterity],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.mushroomRisotto,
// 		name: "Mushroom Risotto",
// 		description: "A creamy risotto made with rare mushrooms. Restores stamina and boosts willpower.",
// 		type: ConsumableType.food,
// 		image: "/images/items/mushroomRisotto.png",
// 		cost: 57,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.willpower],
// 		baseEffectMagnitude: 12,
// 		baseEffectDuration: 8,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.smokedVenison,
// 		name: "Smoked Venison",
// 		description: "A hearty piece of smoked venison, ideal for adventurers. Restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/smokedVenison.png",
// 		cost: 65,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreHealth, ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 22,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.wildBoarSteak,
// 		name: "Wild Boar Steak",
// 		description: "A thick-cut wild boar steak, restores stamina and boosts strength.",
// 		type: ConsumableType.food,
// 		image: "/images/items/wildBoarSteak.png",
// 		cost: 68,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.strength],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 8,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.stuffedBellPeppers,
// 		name: "Stuffed Bell Peppers",
// 		description: "Bell peppers stuffed with seasoned meat and rice. Restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/stuffedBellPeppers.png",
// 		cost: 60,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.goldenBerryTart,
// 		name: "Golden Berry Tart",
// 		description: "A sweet tart made from rare golden berries. Restores stamina and boosts luck.",
// 		type: ConsumableType.food,
// 		image: "/images/items/goldenBerryTart.png",
// 		cost: 55,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.luck],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.candiedNuts,
// 		name: "Candied Nuts",
// 		description: "A crunchy snack of candied nuts. Restores stamina.",
// 		type: ConsumableType.food,
// 		image: "/images/items/candiedNuts.png",
// 		cost: 50,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.roastedHerbPotatoes,
// 		name: "Roasted Herb Potatoes",
// 		description: "Potatoes roasted with a blend of wild herbs. Restores stamina and boosts endurance.",
// 		type: ConsumableType.food,
// 		image: "/images/items/roastedHerbPotatoes.png",
// 		cost: 52,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.endurance],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.honeyGlazedDuck,
// 		name: "Honey-Glazed Duck",
// 		description: "A roasted duck glazed with honey, restores stamina and health.",
// 		type: ConsumableType.food,
// 		image: "/images/items/honeyGlazedDuck.png",
// 		cost: 65,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreHealth, ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 25,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.citrusCuredHam,
// 		name: "Citrus-Cured Ham",
// 		description: "A tangy and savory ham cured in citrus juices. Restores stamina and boosts vitality.",
// 		type: ConsumableType.food,
// 		image: "/images/items/citrusCuredHam.png",
// 		cost: 68,
// 		weight: 2,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),

//     // Uncommon Drinks
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.elvenWine,
// 		name: "Elven Wine",
// 		description: "A mystical wine that restores mana and boosts intelligence.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/elvenWine.png",
// 		cost: 72,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.resportMana, ConsumableEffect.intelligence],
// 		baseEffectMagnitude: 20,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.dwarvenStout,
// 		name: "Dwarven Stout",
// 		description: "A strong drink that boosts strength and restores stamina.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/dwarvenStout.png",
// 		cost: 70,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.strength, ConsumableEffect.restoreStamina],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.spicedMulledWine,
// 		name: "Spiced Mulled Wine",
// 		description: "A warm wine that restores stamina and boosts willpower.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/spicedMulledWine.png",
// 		cost: 65,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.willpower],
// 		baseEffectMagnitude: 18,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.enchantedSpringWater,
// 		name: "Enchanted Spring Water",
// 		description: "Magical water that restores both health and mana.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/enchantedSpringWater.png",
// 		cost: 75,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreHealth, ConsumableEffect.resportMana],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.sparklingCitrusJuice,
// 		name: "Sparkling Citrus Juice",
// 		description: "A refreshing juice that restores stamina and boosts vitality.",
// 		type: ConsumableType.drink,
// 		image: "/images/items/sparklingCitrusJuice.png",
// 		cost: 60,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.vitality],
// 		baseEffectMagnitude: 12,
// 		baseEffectDuration: 6,
// 		consumedAfterUse: true,
// 	}),

// 	// Uncommon Potions
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.strongHealingPotion,
// 		name: "Strong Healing Potion",
// 		description: "A potent healing potion that restores a large amount of health.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/strongHealingPotion.png",
// 		cost: 65,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 35,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.energyElixir,
// 		name: "Energy Elixir",
// 		description: "An invigorating elixir that restores stamina and boosts agility.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/energyElixir.png",
// 		cost: 70,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.restoreStamina, ConsumableEffect.agility],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 8,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.focusTonic,
// 		name: "Focus Tonic",
// 		description: "A tonic that sharpens the mind, boosting intelligence and restoring mana.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/focusTonic.png",
// 		cost: 68,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.intelligence, ConsumableEffect.resportMana],
// 		baseEffectMagnitude: 15,
// 		baseEffectDuration: 8,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.manaElixir,
// 		name: "Mana Elixir",
// 		description: "A powerful elixir that restores a large amount of mana.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/manaElixir.png",
// 		cost: 72,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.resportMana],
// 		baseEffectMagnitude: 35,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.antidoteBrew,
// 		name: "Antidote Brew",
// 		description: "A concoction that neutralizes most common poisons.",
// 		type: ConsumableType.potion,
// 		image: "/images/items/antidoteBrew.png",
// 		cost: 60,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.permanent_endurance, ConsumableEffect.restoreHealth],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 0,
// 		consumedAfterUse: true,
// 	}),

// 	// Uncommon Salves
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.rejuvenatingSalve,
// 		name: "Rejuvenating Salve",
// 		description: "A healing salve that speeds up recovery of health over time.",
// 		type: ConsumableType.salve,
// 		image: "/images/items/rejuvenatingSalve.png",
// 		cost: 55,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.regenerateHealth],
// 		baseEffectMagnitude: 20,
// 		baseEffectDuration: 10,
// 		consumedAfterUse: true,
// 	}),
// 	new ItemConsumableArchetype({
// 		id: ItemConsumableEnum.fireResistantOintment,
// 		name: "Fire Resistant Ointment",
// 		description: "An ointment that grants temporary resistance to fire damage.",
// 		type: ConsumableType.salve,
// 		image: "/images/items/fireResistantOintment.png",
// 		cost: 60,
// 		weight: 1,
// 		tier: Tier.uncommon,
// 		effects: [ConsumableEffect.fireDef],
// 		baseEffectMagnitude: 10,
// 		baseEffectDuration: 12,
// 		consumedAfterUse: true,
// 	}),

//     // MARK: Rare
//     // Rare Foods
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.phoenixEggOmelette,
//         name: "Phoenix Egg Omelette",
//         description: "A luxurious omelette made from a rare Phoenix egg, granting a temporary health regeneration boost.",
//         type: ConsumableType.food,
//         image: "/images/items/phoenixEggOmelette.png",
//         cost: 450,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.regenerateHealth, ConsumableEffect.vitality],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.truffleSteak,
//         name: "Truffle Steak",
//         description: "A perfectly cooked steak infused with rare truffles, increasing strength and stamina.",
//         type: ConsumableType.food,
//         image: "/images/items/truffleSteak.png",
//         cost: 400,
//         weight: 2,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.strength, ConsumableEffect.restoreStamina],
//         baseEffectMagnitude: 18,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.starfruitSorbet,
//         name: "Starfruit Sorbet",
//         description: "A refreshing sorbet made from starfruit, boosting agility and arcane aptitude temporarily.",
//         type: ConsumableType.food,
//         image: "/images/items/starfruitSorbet.png",
//         cost: 350,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.agility, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 17,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.enchantedPumpkinPie,
//         name: "Enchanted Pumpkin Pie",
//         description: "A magical pie made from enchanted pumpkins, granting a temporary boost to luck and charisma.",
//         type: ConsumableType.food,
//         image: "/images/items/enchantedPumpkinPie.png",
//         cost: 380,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.luck, ConsumableEffect.charisma],
//         baseEffectMagnitude: 15,
//         baseEffectDuration: 6,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.celestialLambRoast,
//         name: "Celestial Lamb Roast",
//         description: "A tender roast infused with celestial herbs, boosting vitality and health regeneration.",
//         type: ConsumableType.food,
//         image: "/images/items/celestialLambRoast.png",
//         cost: 420,
//         weight: 2,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.vitality, ConsumableEffect.regenerateHealth],
//         baseEffectMagnitude: 22,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.emberGrilledEel,
//         name: "Ember Grilled Eel",
//         description: "A flavorful eel grilled with ember spice, enhancing fire affinity and strength.",
//         type: ConsumableType.food,
//         image: "/images/items/emberGrilledEel.png",
//         cost: 390,
//         weight: 2,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.strength, ConsumableEffect.strength],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.frostLotusSalad,
//         name: "Frost Lotus Salad",
//         description: "A crisp salad made with frost lotus petals, granting resistance to cold and water affinity.",
//         type: ConsumableType.food,
//         image: "/images/items/frostLotusSalad.png",
//         cost: 370,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.breath, ConsumableEffect.waterDef],
//         baseEffectMagnitude: 18,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.dragonTailStew,
//         name: "Dragon Tail Stew",
//         description: "A hearty stew made from dragon tail, boosting fire resistance and physical defense.",
//         type: ConsumableType.food,
//         image: "/images/items/dragonTailStew.png",
//         cost: 410,
//         weight: 2,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.fire, ConsumableEffect.pDEF],
//         baseEffectMagnitude: 23,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.lavaSpiceCrab,
//         name: "Lava Spice Crab",
//         description: "A delicacy spiced with lava peppers, increasing fire resistance and agility.",
//         type: ConsumableType.food,
//         image: "/images/items/lavaSpiceCrab.png",
//         cost: 380,
//         weight: 2,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.fire, ConsumableEffect.agility],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.silverleafSalmon,
//         name: "Silverleaf Salmon",
//         description: "A delicate salmon dish garnished with silverleaf, boosting intelligence and water affinity.",
//         type: ConsumableType.food,
//         image: "/images/items/silverleafSalmon.png",
//         cost: 400,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.regenerateHealth],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),

//     // Rare Drinks
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.sunfireAle,
//         name: "Sunfire Ale",
//         description: "An ale infused with sunlight, boosting fire elemental affinity and willpower.",
//         type: ConsumableType.drink,
//         image: "/images/items/sunfireAle.png",
//         cost: 250,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.fire, ConsumableEffect.willpower],
//         baseEffectMagnitude: 18,
//         baseEffectDuration: 6,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.moonlightTea,
//         name: "Moonlight Tea",
//         description: "A soothing tea brewed under moonlight, enhancing intelligence and arcane abilities.",
//         type: ConsumableType.drink,
//         image: "/images/items/moonlightTea.png",
//         cost: 300,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 17,
//         baseEffectDuration: 6,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.frozenWine,
//         name: "Frozen Wine",
//         description: "A magical wine chilled with ice magic, increasing cold resistance and water affinity.",
//         type: ConsumableType.drink,
//         image: "/images/items/frozenWine.png",
//         cost: 280,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.water, ConsumableEffect.geo],
//         baseEffectMagnitude: 19,
//         baseEffectDuration: 6,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.mysticElixir,
//         name: "Mystic Elixir",
//         description: "An elixir that enhances mental clarity and boosts magical power.",
//         type: ConsumableType.drink,
//         image: "/images/items/mysticElixir.png",
//         cost: 400,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.regenerateMana],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.arcaneBrew,
//         name: "Arcane Brew",
//         description: "A powerful brew that boosts arcane abilities and defense.",
//         type: ConsumableType.drink,
//         image: "/images/items/arcaneBrew.png",
//         cost: 350,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.mATK, ConsumableEffect.mDEF],
//         baseEffectMagnitude: 22,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//       // Rare Potions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.elixirOfThePhoenix,
//         name: "Elixir of the Phoenix",
//         description: "A legendary elixir that grants the user temporary regeneration and fire resistance.",
//         type: ConsumableType.potion,
//         image: "/images/items/elixirOfThePhoenix.png",
//         cost: 300,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.regenerateHealth, ConsumableEffect.regenerateStamina],
//         baseEffectMagnitude: 25,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.manaRegenerationPotion,
//         name: "Mana Regeneration Potion",
//         description: "A potion that slowly restores mana over time.",
//         type: ConsumableType.potion,
//         image: "/images/items/manaRegenerationPotion.png",
//         cost: 280,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.regenerateMana],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.giantStrengthPotion,
//         name: "Giant Strength Potion",
//         description: "This potion greatly enhances physical strength for a short duration.",
//         type: ConsumableType.potion,
//         image: "/images/items/giantStrengthPotion.png",
//         cost: 320,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.strength],
//         baseEffectMagnitude: 30,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.stormEssencePotion,
//         name: "Storm Essence Potion",
//         description: "A potion that grants affinity with lightning and boosts agility.",
//         type: ConsumableType.potion,
//         image: "/images/items/stormEssencePotion.png",
//         cost: 400,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.air, ConsumableEffect.agility],
//         baseEffectMagnitude: 25,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.shadowVeilPotion,
//         name: "Shadow Veil Potion",
//         description: "This potion allows the user to become almost invisible, greatly improving dodge and stealth.",
//         type: ConsumableType.potion,
//         image: "/images/items/shadowVeilPotion.png",
//         cost: 380,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.dodge, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 28,
//         baseEffectDuration: 9,
//         consumedAfterUse: true,
//     }),

//     // Rare Salves
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.ethericHealingSalve,
//         name: "Etheric Healing Salve",
//         description: "A potent salve that accelerates healing and increases mana regeneration.",
//         type: ConsumableType.salve,
//         image: "/images/items/ethericHealingSalve.png",
//         cost: 350,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.restoreHealth, ConsumableEffect.regenerateMana],
//         baseEffectMagnitude: 22,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.shadowGuardSalve,
//         name: "Shadow Guard Salve",
//         description: "A magical salve that enhances defense against dark and shadow elements.",
//         type: ConsumableType.salve,
//         image: "/images/items/shadowGuardSalve.png",
//         cost: 320,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.chaosDef, ConsumableEffect.mDEF],
//         baseEffectMagnitude: 24,
//         baseEffectDuration: 9,
//         consumedAfterUse: true,
//     }),

//     // Rare Oils
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.dragonOil,
//         name: "Dragon Oil",
//         description: "An enchanted oil that increases fire affinity and can be applied to weapons for a fire attack bonus.",
//         type: ConsumableType.oil,
//         image: "/images/items/dragonOil.png",
//         cost: 300,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.fireDef, ConsumableEffect.chiWarmATK],
//         baseEffectMagnitude: 27,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.frostbiteOil,
//         name: "Frostbite Oil",
//         description: "This oil grants cold resistance and can be applied to weapons for a frost attack bonus.",
//         type: ConsumableType.oil,
//         image: "/images/items/frostbiteOil.png",
//         cost: 320,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.waterDef, ConsumableEffect.orderDef],
//         baseEffectMagnitude: 25,
//         baseEffectDuration: 7,
//         consumedAfterUse: true,
//     }),

//     // Rare Coating Solutions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.arcaneResonanceCoating,
//         name: "Arcane Resonance Coating",
//         description: "A powerful coating that increases magic power and grants resistance to arcane damage.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/arcaneResonanceCoating.png",
//         cost: 400,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.mATK, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 28,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.solarflareCoating,
//         name: "Solarflare Coating",
//         description: "A rare coating that enhances fire defense and grants radiant power to attacks.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/solarflareCoating.png",
//         cost: 380,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.fireDef, ConsumableEffect.pATK],
//         baseEffectMagnitude: 29,
//         baseEffectDuration: 9,
//         consumedAfterUse: true,
//     }),

//     // Rare Runes
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfFortitude,
//         name: "Rune of Fortitude",
//         description: "A powerful rune that boosts the user's endurance and strength for a limited time.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfFortitude.png",
//         cost: 400,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.strength, ConsumableEffect.endurance],
//         baseEffectMagnitude: 30,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfTheStorm,
//         name: "Rune of the Storm",
//         description: "A rune that imbues the user with the power of the storm, boosting lightning attacks and agility.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfTheStorm.png",
//         cost: 380,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.air, ConsumableEffect.agility],
//         baseEffectMagnitude: 32,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),

//     // Rare Powders
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.elementalPowder,
//         name: "Elemental Powder",
//         description: "A magical powder that can be consumed or applied to enhance elemental affinity for a short time.",
//         type: ConsumableType.powder,
//         image: "/images/items/elementalPowder.png",
//         cost: 350,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.fire, ConsumableEffect.water, ConsumableEffect.air],
//         baseEffectMagnitude: 20,
//         baseEffectDuration: 8,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.astralDust,
//         name: "Astral Dust",
//         description: "A rare powder that boosts arcane aptitude and temporarily enhances intelligence.",
//         type: ConsumableType.powder,
//         image: "/images/items/astralDust.png",
//         cost: 400,
//         weight: 1,
//         tier: Tier.rare,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.intelligence],
//         baseEffectMagnitude: 30,
//         baseEffectDuration: 9,
//         consumedAfterUse: true,
//     }),

//     //MARK:: Epic
//     // Epic Food
//   new ItemConsumableArchetype({
//     id: ItemConsumableEnum.celestialFruitSalad,
//     name: "Celestial Fruit Salad",
//     description: "A divine mix of fruits from the heavens, boosting vitality and intelligence.",
//     type: ConsumableType.food,
//     image: "/images/items/celestialFruitSalad.png",
//     cost: 500,
//     weight: 1,
//     tier: Tier.epic,
//     effects: [ConsumableEffect.vitality, ConsumableEffect.intelligence],
//     baseEffectMagnitude: 40,
//     baseEffectDuration: 12,
//     consumedAfterUse: true,
//   }),
//   new ItemConsumableArchetype({
//     id: ItemConsumableEnum.leviathanSteak,
//     name: "Leviathan Steak",
//     description: "A rich steak cut from the legendary sea beast, enhancing strength and endurance.",
//     type: ConsumableType.food,
//     image: "/images/items/leviathanSteak.png",
//     cost: 550,
//     weight: 2,
//     tier: Tier.epic,
//     effects: [ConsumableEffect.strength, ConsumableEffect.endurance],
//     baseEffectMagnitude: 45,
//     baseEffectDuration: 10,
//     consumedAfterUse: true,
//   }),
//   new ItemConsumableArchetype({
//     id: ItemConsumableEnum.draconicSpicePlatter,
//     name: "Draconic Spice Platter",
//     description: "A platter infused with dragon spices that enhances both fire affinity and vitality.",
//     type: ConsumableType.food,
//     image: "/images/items/draconicSpicePlatter.png",
//     cost: 600,
//     weight: 2.5,
//     tier: Tier.epic,
//     effects: [ConsumableEffect.strength, ConsumableEffect.vitality],
//     baseEffectMagnitude: 50,
//     baseEffectDuration: 10,
//     consumedAfterUse: true,
//   }),

//   // Epic Drinks
//   new ItemConsumableArchetype({
//     id: ItemConsumableEnum.etherealElixir,
//     name: "Ethereal Elixir",
//     description: "A radiant drink that grants temporary invisibility and boosts agility.",
//     type: ConsumableType.drink,
//     image: "/images/items/etherealElixir.png",
//     cost: 600,
//     weight: 0.5,
//     tier: Tier.epic,
//     effects: [ConsumableEffect.dodge, ConsumableEffect.agility],
//     baseEffectMagnitude: 45,
//     baseEffectDuration: 12,
//     consumedAfterUse: true,
//   }),
//   new ItemConsumableArchetype({
//     id: ItemConsumableEnum.voidwine,
//     name: "Voidwine",
//     description: "A mystical brew that enhances planar affinity and mana regeneration.",
//     type: ConsumableType.drink,
//     image: "/images/items/voidwine.png",
//     cost: 650,
//     weight: 0.5,
//     tier: Tier.epic,
//     effects: [ConsumableEffect.permanent_planar, ConsumableEffect.regenerateMana],
//     baseEffectMagnitude: 50,
//     baseEffectDuration: 10,
//     consumedAfterUse: true,
//   }),

//   // Epic Potions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.soulfirePotion,
//         name: "Soulfire Potion",
//         description: "A potent potion that grants fire resistance and greatly enhances physical attack power.",
//         type: ConsumableType.potion,
//         image: "/images/items/soulfirePotion.png",
//         cost: 700,
//         weight: 0.5,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.fire, ConsumableEffect.pATK],
//         baseEffectMagnitude: 55,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.starryNightDraught,
//         name: "Starry Night Draught",
//         description: "This potion enhances mana and boosts arcane aptitude.",
//         type: ConsumableType.potion,
//         image: "/images/items/starryNightDraught.png",
//         cost: 680,
//         weight: 0.4,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.permanent_boostMaxMana, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 50,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.chiHarmonyElixir,
//         name: "Chi Harmony Elixir",
//         description: "An elixir that balances both chi warm and chi cold, enhancing harmony and defense.",
//         type: ConsumableType.potion,
//         image: "/images/items/chiHarmonyElixir.png",
//         cost: 700,
//         weight: 0.6,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.chiWarmDEF, ConsumableEffect.chiColdDEF],
//         baseEffectMagnitude: 52,
//         baseEffectDuration: 11,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.grandArcanePotion,
//         name: "Grand Arcane Potion",
//         description: "A potion that boosts arcane aptitude and increases intelligence.",
//         type: ConsumableType.potion,
//         image: "/images/items/grandArcanePotion.png",
//         cost: 750,
//         weight: 0.4,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.intelligence],
//         baseEffectMagnitude: 60,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),

//     // Epic Salves
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.divineHealingBalm,
//         name: "Divine Healing Balm",
//         description: "A sacred salve that heals wounds rapidly and restores vitality over time.",
//         type: ConsumableType.salve,
//         image: "/images/items/divineHealingBalm.png",
//         cost: 720,
//         weight: 0.5,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.restoreHealth, ConsumableEffect.regenerateHealth],
//         baseEffectMagnitude: 55,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.abyssalSalve,
//         name: "Abyssal Salve",
//         description: "A dark salve that protects against necrotic damage and enhances chaos defense.",
//         type: ConsumableType.salve,
//         image: "/images/items/abyssalSalve.png",
//         cost: 740,
//         weight: 0.5,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.chaosDef, ConsumableEffect.mDEF],
//         baseEffectMagnitude: 58,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),

//     // Epic Oils
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.celestialBladeOil,
//         name: "Celestial Blade Oil",
//         description: "An oil that enhances weapon power and boosts physical attacks with radiant energy.",
//         type: ConsumableType.oil,
//         image: "/images/items/celestialBladeOil.png",
//         cost: 750,
//         weight: 0.6,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.pATK, ConsumableEffect.pCRT],
//         baseEffectMagnitude: 60,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.infernoOil,
//         name: "Inferno Oil",
//         description: "This oil imbues weapons with the power of eternal flame, increasing fire damage.",
//         type: ConsumableType.oil,
//         image: "/images/items/infernoOil.png",
//         cost: 760,
//         weight: 0.5,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.fire, ConsumableEffect.chiWarmATK],
//         baseEffectMagnitude: 62,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),

//     // Epic Coating Solutions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.phoenixWingCoating,
//         name: "Phoenix Wing Coating",
//         description: "A mystical coating that grants temporary fire immunity and enhances agility.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/phoenixWingCoating.png",
//         cost: 780,
//         weight: 0.5,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.fire, ConsumableEffect.agility],
//         baseEffectMagnitude: 65,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.froststormCoating,
//         name: "Froststorm Coating",
//         description: "A powerful coating that enhances cold resistance and boosts frost-based attacks.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/froststormCoating.png",
//         cost: 790,
//         weight: 0.5,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.mATK, ConsumableEffect.chiColdATK],
//         baseEffectMagnitude: 60,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),

//     // Epic Runes
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfTranscendence,
//         name: "Rune of Transcendence",
//         description: "A powerful rune that grants a significant boost to all stats for a limited time.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfTranscendence.png",
//         cost: 850,
//         weight: 0.3,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.strength, ConsumableEffect.intelligence, ConsumableEffect.endurance],
//         baseEffectMagnitude: 70,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfTheVoid,
//         name: "Rune of the Void",
//         description: "A forbidden rune that increases chaos affinity and grants void-based powers.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfTheVoid.png",
//         cost: 880,
//         weight: 0.3,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.chaos, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 75,
//         baseEffectDuration: 10,
//         consumedAfterUse: true,
//     }),

//     // Epic Powder
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.essenceOfDragonscale,
//         name: "Essence of Dragonscale",
//         description: "A potent powder made from dragon scales, boosting defense and strength.",
//         type: ConsumableType.powder,
//         image: "/images/items/essenceOfDragonscale.png",
//         cost: 810,
//         weight: 0.2,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.pDEF, ConsumableEffect.strength],
//         baseEffectMagnitude: 65,
//         baseEffectDuration: 11,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.celestialGlowPowder,
//         name: "Celestial Glow Powder",
//         description: "A magical powder that boosts willpower and grants light affinity.",
//         type: ConsumableType.powder,
//         image: "/images/items/celestialGlowPowder.png",
//         cost: 820,
//         weight: 0.2,
//         tier: Tier.epic,
//         effects: [ConsumableEffect.order, ConsumableEffect.willpower],
//         baseEffectMagnitude: 68,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),

//     //MARK:: Legendary
//     // Legendary Food
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.ambrosiaFeast,
//         name: "Ambrosia Feast",
//         description: "A divine meal capable of restoring all health, stamina, and granting a permanent stat boost.",
//         type: ConsumableType.food,
//         image: "/images/items/ambrosiaFeast.png",
//         cost: 4500,
//         weight: 2,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.restoreHealth, ConsumableEffect.restoreStamina, ConsumableEffect.permanent_boostMaxHealth],
//         baseEffectMagnitude: 150,
//         baseEffectDuration: 0, // Permanent effect
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.worldTreeFruit,
//         name: "World Tree Fruit",
//         description: "A rare fruit from the World Tree, granting immense vitality and elemental resistance.",
//         type: ConsumableType.food,
//         image: "/images/items/worldTreeFruit.png",
//         cost: 4800,
//         weight: 1.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.vitality, ConsumableEffect.permanent_boostMaxHealth, ConsumableEffect.order],
//         baseEffectMagnitude: 140,
//         baseEffectDuration: 12, // Boost effect duration
//         consumedAfterUse: true,
//     }),

//     // Legendary Drinks
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.draughtOfImmortality,
//         name: "Draught of Immortality",
//         description: "A legendary drink that extends life and boosts vitality permanently.",
//         type: ConsumableType.drink,
//         image: "/images/items/draughtOfImmortality.png",
//         cost: 5000,
//         weight: 0.8,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.vitality, ConsumableEffect.permanent_vitality],
//         baseEffectMagnitude: 160,
//         baseEffectDuration: 0, // Permanent vitality boost
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.elixirOfTheSun,
//         name: "Elixir of the Sun",
//         description: "A radiant elixir that enhances light affinity and intelligence.",
//         type: ConsumableType.drink,
//         image: "/images/items/elixirOfTheSun.png",
//         cost: 4800,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.fire],
//         baseEffectMagnitude: 150,
//         baseEffectDuration: 14,
//         consumedAfterUse: true,
//     }),

//     // Legendary Potions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.dragonHeartElixir,
//         name: "Dragon Heart Elixir",
//         description: "An elixir brewed from the heart of a dragon, granting immense strength and fire resistance.",
//         type: ConsumableType.potion,
//         image: "/images/items/dragonHeartElixir.png",
//         cost: 6000,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.permanent_strength, ConsumableEffect.permanent_fire],
//         baseEffectMagnitude: 180,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.essenceOfLight,
//         name: "Essence of Light",
//         description: "A potion that greatly enhances light magic, granting the user radiant power.",
//         type: ConsumableType.potion,
//         image: "/images/items/essenceOfLight.png",
//         cost: 5500,
//         weight: 0.4,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.permanent_order],
//         baseEffectMagnitude: 170,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.celestialManaElixir,
//         name: "Celestial Mana Elixir",
//         description: "A rare elixir that enhances mana regeneration and boosts intelligence.",
//         type: ConsumableType.potion,
//         image: "/images/items/celestialManaElixir.png",
//         cost: 5200,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.permanent_boostMaxMana],
//         baseEffectMagnitude: 160,
//         baseEffectDuration: 14,
//         consumedAfterUse: true,
//     }),

//     // Legendary Salves
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.phoenixAshSalve,
//         name: "Phoenix Ash Salve",
//         description: "A salve made from the ashes of a phoenix, granting healing and rebirth abilities.",
//         type: ConsumableType.salve,
//         image: "/images/items/phoenixAshSalve.png",
//         cost: 6200,
//         weight: 0.7,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.regenerateHealth, ConsumableEffect.restoreHealth],
//         baseEffectMagnitude: 180,
//         baseEffectDuration: 16,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.eternalBloomBalm,
//         name: "Eternal Bloom Balm",
//         description: "A salve made from eternal blooms, granting health regeneration and boosting willpower.",
//         type: ConsumableType.salve,
//         image: "/images/items/eternalBloomBalm.png",
//         cost: 5800,
//         weight: 0.6,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.willpower, ConsumableEffect.regenerateHealth],
//         baseEffectMagnitude: 170,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),

//     // Legendary Oils
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.orichalcumWeaponOil,
//         name: "Orichalcum Weapon Oil",
//         description: "An oil that grants legendary sharpness and boosts physical attack with orichalcum's power.",
//         type: ConsumableType.oil,
//         image: "/images/items/orichalcumWeaponOil.png",
//         cost: 6300,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.pATK, ConsumableEffect.pCRT],
//         baseEffectMagnitude: 190,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.starlightOil,
//         name: "Starlight Oil",
//         description: "An oil that enhances weapon power with the energy of the stars, boosting magical attacks.",
//         type: ConsumableType.oil,
//         image: "/images/items/starlightOil.png",
//         cost: 6400,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.mATK, ConsumableEffect.air],
//         baseEffectMagnitude: 180,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),

//     // Legendary Coating Solutions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.netherVoidCoating,
//         name: "Nether Void Coating",
//         description: "A dark coating that grants powerful void energy to your weapons, enhancing chaos affinity.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/netherVoidCoating.png",
//         cost: 6700,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.chaos, ConsumableEffect.mATK],
//         baseEffectMagnitude: 195,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.lightweaverCoating,
//         name: "Lightweaver Coating",
//         description: "A radiant coating that enhances your weapons with light energy, granting extra dodge and speed.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/lightweaverCoating.png",
//         cost: 6900,
//         weight: 0.5,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.dodge, ConsumableEffect.agility],
//         baseEffectMagnitude: 185,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),

//     // Legendary Runes
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfAscension,
//         name: "Rune of Ascension",
//         description: "A rare rune that greatly enhances intelligence and arcane power.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfAscension.png",
//         cost: 7100,
//         weight: 0.3,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 200,
//         baseEffectDuration: 14,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfTheEternalFlame,
//         name: "Rune of the Eternal Flame",
//         description: "A rune that grants immense fire affinity and permanent boosts to willpower.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfTheEternalFlame.png",
//         cost: 7300,
//         weight: 0.3,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.fire, ConsumableEffect.permanent_willpower],
//         baseEffectMagnitude: 190,
//         baseEffectDuration: 0, // Permanent boost
//         consumedAfterUse: true,
//     }),

//     // Legendary Powder
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.powderedDragonBone,
//         name: "Powdered Dragon Bone",
//         description: "A rare powder made from dragon bones, enhancing strength and defense.",
//         type: ConsumableType.powder,
//         image: "/images/items/powderedDragonBone.png",
//         cost: 7400,
//         weight: 0.2,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.strength, ConsumableEffect.pDEF],
//         baseEffectMagnitude: 195,
//         baseEffectDuration: 12,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.essenceOfTheStars,
//         name: "Essence of the Stars",
//         description: "A magical powder that enhances all elemental affinities and boosts intelligence.",
//         type: ConsumableType.powder,
//         image: "/images/items/essenceOfTheStars.png",
//         cost: 7600,
//         weight: 0.2,
//         tier: Tier.legendary,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.air, ConsumableEffect.fire],
//         baseEffectMagnitude: 200,
//         baseEffectDuration: 13,
//         consumedAfterUse: true,
//     }),

//     //MARK:: Unique
//     // Unique Potions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.voidEssenceElixir,
//         name: "Void Essence Elixir",
//         description: "An elixir imbued with the power of the void, greatly enhancing chaos affinity and magic.",
//         type: ConsumableType.potion,
//         image: "/images/items/voidEssenceElixir.png",
//         cost: 8000,
//         weight: 0.6,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.chaos, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 220,
//         baseEffectDuration: 16,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.oracleGemPotion,
//         name: "Oracle Gem Potion",
//         description: "This potion made from the Oracle Gem grants immense foresight and boosts intelligence.",
//         type: ConsumableType.potion,
//         image: "/images/items/oracleGemPotion.png",
//         cost: 8200,
//         weight: 0.5,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 230,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.abyssalShardBrew,
//         name: "Abyssal Shard Brew",
//         description: "A dark brew made from Abyssal Shards, granting shadow resistance and strength.",
//         type: ConsumableType.potion,
//         image: "/images/items/abyssalShardBrew.png",
//         cost: 8300,
//         weight: 0.5,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.chaos, ConsumableEffect.strength],
//         baseEffectMagnitude: 225,
//         baseEffectDuration: 14,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.titanstoneTonic,
//         name: "Titanstone Tonic",
//         description: "A tonic granting immense physical defense and vitality, derived from Titanstone.",
//         type: ConsumableType.potion,
//         image: "/images/items/titanstoneTonic.png",
//         cost: 8500,
//         weight: 0.7,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.vitality, ConsumableEffect.pDEF],
//         baseEffectMagnitude: 240,
//         baseEffectDuration: 16,
//         consumedAfterUse: true,
//     }),

//     // Unique Salves
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.soulBindingSalve,
//         name: "Soul Binding Salve",
//         description: "A salve with the power to bind souls, granting willpower and health regeneration.",
//         type: ConsumableType.salve,
//         image: "/images/items/soulBindingSalve.png",
//         cost: 8200,
//         weight: 0.6,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.willpower, ConsumableEffect.regenerateHealth],
//         baseEffectMagnitude: 230,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),

//     // Unique Oils
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.titanstoneOil,
//         name: "Titanstone Oil",
//         description: "A potent oil that grants immense physical attack and endurance when applied to weapons.",
//         type: ConsumableType.oil,
//         image: "/images/items/titanstoneOil.png",
//         cost: 8300,
//         weight: 0.6,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.pATK, ConsumableEffect.endurance],
//         baseEffectMagnitude: 235,
//         baseEffectDuration: 14,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.spiritwoodOil,
//         name: "Spiritwood Oil",
//         description: "A mystical oil that enhances elemental affinities, especially with earth and vitality.",
//         type: ConsumableType.oil,
//         image: "/images/items/spiritwoodOil.png",
//         cost: 8500,
//         weight: 0.5,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.geo, ConsumableEffect.vitality],
//         baseEffectMagnitude: 230,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),

//     // Unique Coating Solutions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.heartwoodCoating,
//         name: "Heartwood Coating",
//         description: "A rare coating made from Heartwood, granting physical defense and vitality when applied.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/heartwoodCoating.png",
//         cost: 8700,
//         weight: 0.5,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.vitality, ConsumableEffect.pDEF],
//         baseEffectMagnitude: 240,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.timeweaverSilkCoating,
//         name: "Timeweaver Silk Coating",
//         description: "A magical coating made from Timeweaver Silk, enhancing dexterity and arcane power.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/timeweaverSilkCoating.png",
//         cost: 9000,
//         weight: 0.4,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.dexterity, ConsumableEffect.arcaneaptitude_plus],
//         baseEffectMagnitude: 250,
//         baseEffectDuration: 14,
//         consumedAfterUse: true,
//     }),

//     // Unique Runes
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfEternalHarmony,
//         name: "Rune of Eternal Harmony",
//         description: "A powerful rune that greatly boosts planar energy and grants intelligence.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfEternalHarmony.png",
//         cost: 8800,
//         weight: 0.3,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.planar, ConsumableEffect.intelligence],
//         baseEffectMagnitude: 260,
//         baseEffectDuration: 16,
//         consumedAfterUse: true,
//     }),

//     // Unique Powders
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.abyssWeavePowder,
//         name: "Abyss Weave Powder",
//         description: "A powder made from the finest Abyss Weave, enhancing chaos and dexterity.",
//         type: ConsumableType.powder,
//         image: "/images/items/abyssWeavePowder.png",
//         cost: 8600,
//         weight: 0.2,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.chaos, ConsumableEffect.dexterity],
//         baseEffectMagnitude: 245,
//         baseEffectDuration: 15,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.oracleGemDust,
//         name: "Oracle Gem Dust",
//         description: "A mystical powder made from crushed Oracle Gems, boosting foresight and intelligence.",
//         type: ConsumableType.powder,
//         image: "/images/items/oracleGemDust.png",
//         cost: 8900,
//         weight: 0.2,
//         tier: Tier.unique,
//         effects: [ConsumableEffect.intelligence, ConsumableEffect.luck],
//         baseEffectMagnitude: 250,
//         baseEffectDuration: 16,
//         consumedAfterUse: true,
//     }),

//     //MARK:: DIVINE
//     // Divine Food
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.ambrosiaSoup,
//         name: "Ambrosia Soup",
//         description: "A legendary dish that is said to grant vitality and extend life.",
//         type: ConsumableType.food,
//         image: "/images/items/ambrosiaSoup.png",
//         cost: 30000,
//         weight: 1.0,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.vitality, ConsumableEffect.permanent_boostMaxHealth],
//         baseEffectMagnitude: 400,
//         baseEffectDuration: 0, // Permanent boost
//         consumedAfterUse: true,
//     }),

//     // Divine Potions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.godsbloodPotion,
//         name: "Godsblood Potion",
//         description: "This potion contains the essence of the gods, granting divine protection and power.",
//         type: ConsumableType.potion,
//         image: "/images/items/godsbloodPotion.png",
//         cost: 35000,
//         weight: 0.5,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.willpower],
//         baseEffectMagnitude: 450,
//         baseEffectDuration: 20,
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.essenceOfEternity,
//         name: "Essence of Eternity",
//         description: "A potion infused with the essence of eternity, it grants everlasting mana and boosts intelligence.",
//         type: ConsumableType.potion,
//         image: "/images/items/essenceOfEternity.png",
//         cost: 38000,
//         weight: 0.5,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.permanent_boostMaxMana, ConsumableEffect.intelligence],
//         baseEffectMagnitude: 430,
//         baseEffectDuration: 0, // Permanent mana boost
//         consumedAfterUse: true,
//     }),
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.celestialTearsPotion,
//         name: "Celestial Tears Potion",
//         description: "Tears from celestial beings, this potion greatly enhances elemental magic and vitality.",
//         type: ConsumableType.potion,
//         image: "/images/items/celestialTearsPotion.png",
//         cost: 37000,
//         weight: 0.5,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.water, ConsumableEffect.vitality],
//         baseEffectMagnitude: 420,
//         baseEffectDuration: 18,
//         consumedAfterUse: true,
//     }),

//     // Divine Salves
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.galaxyDustSalve,
//         name: "Galaxy Dust Salve",
//         description: "A salve made from the dust of galaxies, it grants incredible regenerative powers.",
//         type: ConsumableType.salve,
//         image: "/images/items/galaxyDustSalve.png",
//         cost: 34000,
//         weight: 0.6,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.regenerateHealth, ConsumableEffect.permanent_boostMaxHealth],
//         baseEffectMagnitude: 440,
//         baseEffectDuration: 0, // Permanent health boost
//         consumedAfterUse: true,
//     }),

//     // Divine Coating Solutions
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.aetheriumCoating,
//         name: "Aetherium Coating",
//         description: "An ethereal coating that enhances weapon power and grants elemental resistance.",
//         type: ConsumableType.coatingSolution,
//         image: "/images/items/aetheriumCoating.png",
//         cost: 36000,
//         weight: 0.4,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.pATK, ConsumableEffect.air],
//         baseEffectMagnitude: 430,
//         baseEffectDuration: 19,
//         consumedAfterUse: true,
//     }),

//     // Divine Runes
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.runeOfAether,
//         name: "Rune of Aether",
//         description: "A powerful rune that connects the bearer to the Aether, enhancing magic and agility.",
//         type: ConsumableType.rune,
//         image: "/images/items/runeOfAether.png",
//         cost: 40000,
//         weight: 0.3,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.mATK, ConsumableEffect.agility],
//         baseEffectMagnitude: 450,
//         baseEffectDuration: 20,
//         consumedAfterUse: true,
//     }),

//     // Divine Powders
//     new ItemConsumableArchetype({
//         id: ItemConsumableEnum.stardustPowder,
//         name: "Stardust Powder",
//         description: "A powder made from the very dust of stars, boosting arcane power and intelligence.",
//         type: ConsumableType.powder,
//         image: "/images/items/stardustPowder.png",
//         cost: 38000,
//         weight: 0.2,
//         tier: Tier.divine,
//         effects: [ConsumableEffect.arcaneaptitude_plus, ConsumableEffect.intelligence],
//         baseEffectMagnitude: 450,
//         baseEffectDuration: 19,
//         consumedAfterUse: true,
//     }),
// ];

// export async function createItemConsumableTableIfNotExists() {
//     const tableName = 'ItemConsumables';
//     const tableStructure = `
//          id TEXT PRIMARY KEY,
//         name TEXT NOT NULL,
//         description TEXT,
//         type TEXT,
//         image TEXT,
//         cost INTEGER,
//         weight INTEGER,
//         tier TEXT,
//         effects TEXT,
//         baseEffectMagnitude INTEGER,
//         baseEffectDuration INTEGER,
//         consumedAfterUse BOOLEAN
//     `;
    
//     await createTableIfNotExists(tableName, tableStructure, ItemConsumableSeed, 'id')
// }